(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var D3=function(a){a.ea("cardstatechange",a.Dh()&&a.Ck()?1:0)},E3=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},KSa=function(a){var b=g.jn(a);
a=g.pn(a);return new g.Wm(b.x,b.y,a.width,a.height)},LSa=function(a){return Math.pow(a,3)},MSa=function(a){return 3*a*a-2*a*a*a},H3=function(a){a=g.Pa(a);
delete F3[a];g.Te(F3)&&G3&&G3.stop()},OSa=function(){G3||(G3=new g.L(function(){NSa()},20));
var a=G3;a.isActive()||a.start()},NSa=function(){var a=g.Sa();
g.Ge(F3,function(b){PSa(b,a)});
g.Te(F3)||OSa()},I3=function(a,b,c,d){g.ms.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},PSa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;QSa(a,a.progress);1==a.progress?(a.i=0,H3(a),a.onFinish(),a.Nw()):a.Hc()&&a.vC()},QSa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},RSa=function(a,b){g.ye.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},J3=function(a,b,c,d,e){I3.call(this,b,c,d,e);
this.element=a},K3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
J3.call(this,a,b,c,d,e)},L3=function(a){g.G.call(this);
this.u=a||window;this.i=[]},M3=function(a){return a.baseUrl||null},N3=function(a,b){return g.iq(g.Vn(a,b,void 0),function(c){return!!c})},SSa=function(a,b,c){function d(K){var pa,La,sb,lb=K.hovercardButton;
if(!lb)return null;lb=lb.subscribeButtonRenderer;if(!lb)return null;var nb=f(lb.unsubscribedButtonText),Wb=f(lb.subscribedButtonText);if(lb.subscribed){var Qa=f(lb.subscriberCountWithUnsubscribeText);var bd=f(lb.subscriberCountText)}else Qa=f(lb.subscriberCountText),bd=f(lb.subscriberCountWithSubscribeText);var Nb=null;return K.signinEndpoint&&(Nb=E3(K,"signinEndpoint","webNavigationEndpointData","url"),Nb||(Nb=null===(sb=null===(La=null===(pa=lb.signInEndpoint)||void 0===pa?void 0:pa.commandMetadata)||
void 0===La?void 0:La.webCommandMetadata)||void 0===sb?void 0:sb.url),!Nb)?null:nb&&(Wb||Nb)?{subscribed:lb.subscribed,subscribeText:nb,subscribeCount:Qa,unsubscribeText:Wb,unsubscribeCount:bd,enabled:lb.enabled,signinUrl:Nb,classic:K.useClassicSubscribeButton}:null}
function e(K){if(K){var pa=[],La=K.videoId;La&&pa.push("v="+La);(La=K.playlistId)&&pa.push("list="+La);(K=K.startTimeSeconds)&&pa.push("t="+K);return"/watch?"+pa.join("&")}}
function f(K){if(!K)return null;var pa=K.simpleText;return pa?pa:K.runs?g.Vn(K.runs,function(La){return La.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,v=null,x=!1,y=null,z=null,D=null,H=null,F=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=E3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((D=E3(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(F=f(b.additionalFeesText)),(n=E3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=E3(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,W="";if(b.metadata){var Z=f(b.metadata);Z&&(W=Z)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),rK:b.image,
iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:v,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,rT:n,sessionData:J?{itct:J}:null,dY:p,Qu:a?a:null,uT:b.isPlaceholder,impressionUrls:N3(b.impressionUrls||[],M3),kT:N3(b.hovercardShowUrls||[],M3),clickUrls:N3(l.loggingUrls||[],M3),visualElement:g.jy(b.trackingParams),
productPrice:H,additionalFeesText:F}},O3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:N3(a.impressionUrls||[],M3),elements:N3(a.elements||[],function(d,e){return SSa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.jy(a.trackingParams));return c},P3=function(a){g.CM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.J=0;a=a.V();this.S=g.pE(a)||g.tE(a);this.events=new g.HC(this);g.I(this,this.events);this.events.T(this.player,g.nz("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.oz("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.zb);this.events.T(window,"focus",this.fX);this.load();var b=g.hh("STYLE");(g.Ug("HEAD")[0]||document.body).appendChild(b);g.xe(this,function(){g.lh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},TSa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},Q3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},USa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=O3(f,TSa(a))));R3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Fq;d&&(c.postParams={ad_tracking:d});if(b=g.fta(b))if(b=g.$f(b),b=g.Sf(b))a.B=g.nu(b,c)},R3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ze("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&VSa(a);c=[];d=new g.lz(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.pM(a.player,a.u.element,4),a.C=new g.UK(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=WSa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.pM(a.player,f.element,4);var h=new g.lz(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);XSa(a,
f,e)}else g.vy(new g.pw("buildEndscreenElement null",e))}a.player.Gd(c);a.zb()}},VSa=function(a){var b=g.my(),c=g.ny();
c&&b&&a.endscreen.visualElement&&g.Ay(void 0,c,b,[a.endscreen.visualElement])},WSa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ja:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Qu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:S3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:T3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ja:["ytp-ce-video-title"].concat(g.u(c)),W:{dir:g.rs(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ja:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Qu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:S3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:T3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ja:["ytp-ce-playlist-title"].concat(g.u(c)),W:{dir:g.rs(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ja:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Qu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ja:["ytp-ce-channel-title","ytp-ce-link"],W:{href:T3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.rs(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ja:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:S3(b)}]};c=new g.V(c);var d=g.Vg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.FN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ja:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Qu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.rs(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ja:["ytp-ce-website-goto","ytp-ce-link"],W:{href:T3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:S3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:YSa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ja:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Qu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.rs(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ja:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:T3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:S3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.V(a)}b.uT&&g.M(c.element,"ytp-ce-placeholder");return c},S3=function(a){if(a.rK)var b=a.rK.thumbnails;
return YSa(b?b[b.length-1].url:null)},YSa=function(a){return a?{style:"background-image: url("+a+")"}:{}},XSa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.M(b.element,"ytp-ce-force-expand"),U3(a,c.id,!0)):(g.ds(b.element,"ytp-ce-force-expand"),g.ds(b.element,"ytp-ce-element-hover"),U3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){V3(a,b,c)});
b.Ra("mouseleave",function(){W3(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){ZSa(a,c,m)});
b.Ra("keypress",function(m){ZSa(a,c,m)});
b.Ra("focus",function(){V3(a,b,c)});
b.Ra("blur",function(){W3(a,b,c)});
b.Ra("touchstart",function(){V3(a,b,c)});
var l=g.Xg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.ds(b.element,"ytp-ce-element-hover");g.ds(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Xg("ytp-sb-subscribe",b.element));d(g.Xg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},ZSa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.bs(d,"ytp-ce-element");){g.bs(d,"subscribe-label")&&X3(a,b);
if(g.bs(d,"ytp-ce-channel-subscribe"))return;d=g.mh(d)}if(!d||g.bs(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])W3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.dY)X3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.$f(T3(a,b.targetUrl)),c=g.Sf(c),g.tL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=T3(a,b.targetUrl),l=b.sessionData,m=g.Zt(h);e&&m&&(m.v||m.list)?a.player.Xj(m.v,l,m.list,!1):
g.sL(h,l)};
X3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},T3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.RE(a)+b}else return"";return b},V3=function(a,b,c){g.bs(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),Y3(a,c.kT),U3(a,c.id,!0))},W3=function(a,b,c){g.ds(b.element,"ytp-ce-element-hover");
g.ds(b.element,"ytp-ce-force-expand");U3(a,c.id,!1)},U3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},Y3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Q3(a))c&&c();else{b=$Sa(a,b);var e=0,f=!1,h=new g.L(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.yv(b[a],d)}},X3=function(a,b,c){Y3(a,b.clickUrls,c);
(a=g.ny())&&b.rT&&g.Gy(a,b.visualElement)},$Sa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(aTa(b[d],c));return a},aTa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},bTa=function(a){return"string"===typeof a?a:""},Z3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},cTa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},$3=function(a){return a.value?a.value:null},a4=function(a){if(!a)return null;
var b=g.$f(bTa(a.value));b=g.Sf(b);if(!b)return null;var c=Z3(a.target,dTa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new cTa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},eTa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},hTa=function(a){if(!a)return null;
var b=Z3(a.type,fTa),c=Z3(a.trigger,gTa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=a4(a?a:null);return b?new eTa(b,c,a):null},iTa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},kTa=function(a){return(a=jTa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},jTa=function(a,b){return g.Ub(a.action,b,void 0)},lTa=function(a,b){this.context=a;
this.i=b},c4=function(a){return a.customMessage?b4("div","iv-card-message",a.customMessage):""},d4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},e4=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(b4("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},b4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.rs(c);return{G:a,W:b,va:c}},mTa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.By&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.By+");");c.dir=g.rs(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ja:b,W:c,U:d}},f4=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},nTa=function(a,b){this.merchant=a;
this.price=b},oTa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},pTa=function(a,b){return b?b:oTa(a)?"current":"new"},g4=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Sa=new Map;this.Va=new Map;this.context.I.addEventListener(g.nz("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.oz("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)})},h4=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.wC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.fb=!1});
a.context.i.Ra(b,"touchmove",function(){a.fb=!0})},qTa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},i4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
zO:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
xB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},l4=function(a,b,c){g4.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ka=this.rb=this.B=this.isInitialized=!1;this.xa=null;this.cards=[];this.ob=this.S=this.Ia=this.D=this.La=this.i=null;this.Z=[];this.K=this.Ie=this.Ba=null;this.J=0;this.Aa=new g.L(g.Ia,c.Y.re?4E3:3E3);g.I(this,this.Aa);this.Za=new g.L(g.Ia);g.I(this,this.Za);this.oa=new lTa(c,function(e,f,h,l,m,n){h4(d,e,f,h,l,m,n)});
this.X=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ja:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.I(this,this.X);this.C=this.X.element;this.Wa=new g.UK(this.X,330);g.I(this,this.Wa);this.jb=g.Xg("iv-drawer-header-text",this.C);this.u=g.Xg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.rb&&j4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.rb=d.B)&&k4(d)})},rTa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){j4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){k4(a)});
var c=b.headerText;g.th(a.jb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.jy(b.trackingParams);a.K=g.jy(b.closeTrackingParams);a.Ie=g.jy(b.iconTrackingParams)},sTa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:m4(a,c,b,d),sponsored:!1,tracking:i4(d,e,d.command),Nl:d.trackingParams?g.jy(d.trackingParams):null,bj:e.trackingParams?
g.jy(e.trackingParams):null,Ie:f&&f.trackingParams?g.jy(f.trackingParams):null,imageUrl:n4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.sz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,By:null,title:d.title?g.sz(d.title):"",customMessage:d.callToAction?g.sz(d.callToAction):"",url:d.command.urlEndpoint.url?a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};o4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:m4(a,c,b,d),sponsored:!1,tracking:i4(d,e,d.endpoint),Nl:d.trackingParams?g.jy(d.trackingParams):null,bj:e.trackingParams?g.jy(e.trackingParams):null,Ie:f&&f.trackingParams?
g.jy(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.sz(d.customText):null,profileImageUrl:n4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.sz(d.channelName):"",metaInfo:[d.subscriberCountText?g.sz(d.subscriberCountText):""],url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
o4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:m4(a,c,b,d),sponsored:!1,tracking:i4(d,e,d.action),Nl:d.trackingParams?g.jy(d.trackingParams):
null,bj:e.trackingParams?g.jy(e.trackingParams):null,Ie:f&&f.trackingParams?g.jy(f.trackingParams):null,Ix:n4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.sz(d.customMessage):null,playlistVideoCount:g.sz(d.playlistVideoCount),title:d.playlistTitle?g.sz(d.playlistTitle):"",metaInfo:[d.channelName?g.sz(d.channelName):"",d.videoCountText?g.sz(d.videoCountText):""],url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:qTa(d.action)})};o4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:m4(a,c,b,d),sponsored:!1,tracking:i4(d,e,d.action),Nl:d.trackingParams?g.jy(d.trackingParams):null,bj:e.trackingParams?g.jy(e.trackingParams):null,Ie:f&&f.trackingParams?g.jy(f.trackingParams):
null,Ix:n4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.sz(d.lengthString):null,customMessage:d.customMessage?g.sz(d.customMessage):null,title:d.videoTitle?g.sz(d.videoTitle):"",metaInfo:[d.channelName?g.sz(d.channelName):"",d.viewCountText?g.sz(d.viewCountText):""],isLiveNow:!!d.badge,url:a4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:qTa(d.action)})};o4(a,b)}a.J++},n4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},m4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},uTa=function(a,b){if(b=tTa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.lh(b.uD),g.cc(a.cards,b),a.Ey(),p4(a)},j4=function(a,b,c){if(!a.B){a.Wa.show();
a.La=new g.L(function(){g.M(a.context.I.getRootNode(),g.kT.IV_DRAWER_OPEN)},0);
a.La.start();a.xa=g.hv(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.ny();d&&a.Ba&&a.K&&g.Ey(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.bM||(f.bM=!0,vTa(a.context.logger,f.card.tracking.impression,b)),d&&g.Ey(d,[f.card.Nl]);D3(a.I);c&&(a.D=new g.L(function(){a.Ia=a.S;a.ob.focus()},330),a.D.start())}},k4=function(a){a.B&&(a.Wa.hide(),g.iv(a.xa),a.xa=null,g.ds(a.context.I.getRootNode(),g.kT.IV_DRAWER_OPEN),a.B=!1,D3(a.I),a.D&&a.D.stop(),a.D=new g.L(function(){a.Ia&&(a.Ia.focus(),a.Ia=null)},330),a.D.start())},
xTa=function(a){g.cs(a.element,[g.kT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.pM(a.I,a.C,5);wTa(a);a.S=g.Xg("ytp-cards-button",a.I.getRootNode());a.ob=g.Xg("iv-drawer-close-button",a.C);a.isInitialized=!0},wTa=function(a){var b=g.Xg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.TR,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.fS,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.bs(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Ev("iv-button-shown",a.zT,a));a.Z.push(g.Ev("iv-button-hidden",a.yT,a));a.Z.push(g.Ev("iv-teaser-shown",a.EQ,a));a.Z.push(g.Ev("iv-teaser-hidden",a.AT,a));a.Z.push(g.Ev("iv-teaser-clicked",a.DQ,a))},o4=function(a,b){a.isInitialized||xTa(a);
uTa(a,b.id);var c=yTa(a,b);if(c){var d={card:b,uD:c.element,bM:!1},e=zTa(a,d);g.ic(a.cards,e,0,d);c.Da(a.u,e);a.Ey();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,p4(a),ATa(a,d),j4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&BTa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){BTa(a,d)}),p4(a))}},yTa=function(a,b){switch(b.type){case "simple":a=a.oa;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=mTa(b);c={G:"div",Ja:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?$3(b.url)||"":""},U:[d4(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[b4("h2",void 0,b.title),d]}]}]};c=new g.V(c);f4(a,g.Wg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={G:"div",Ja:["iv-card","iv-card-channel"],U:[{G:"a",Ja:["iv-click-target"],W:{href:$3(b.url)||"","data-ytid":b.channelId},U:[d4(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[c4(b),{G:"h2",L:"iv-card-primary-link",va:b.title},e4(b)]}]}]},c=new g.V(c),f4(a,g.Wg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={G:"div",Ja:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:$3(b.url)||""},U:[d4(b.Ix,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[c4(b),b4("h2","iv-card-primary-link",b.title),e4(b)]}]}]},c=new g.V(c),
f4(a,g.Wg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.$b(b.offers);c=["iv-card"];d="";var f=mTa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",U:e});e=b.url?$3(b.url)||"":"";c={G:"div",Ja:c,W:{tabindex:"0"},U:[{G:"a",Ja:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[b4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.hh("span");g.th(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.td(d,"adInfo");f4(a,g.Wg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ja:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null,e={G:"div",Ja:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:$3(c))||""},U:[d4(b.Ix,d),{G:"div",L:"iv-card-content",U:[c4(b),b4("h2","iv-card-primary-link",b.title),e4(b),f]}]}]},c=new g.V(e),
f4(a,g.Wg("iv-click-target",c.element),b,b.url),c;default:return null}},zTa=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},CTa=function(a){return a.i?"productListing"===a.i.card.type:g.Wn(a.cards,function(b){return"productListing"===b.card.type})},p4=function(a){g.N(a.I.getRootNode(),"ytp-cards-shopping-active",CTa(a))},BTa=function(a,b){if(!g.bs(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.ny(),d=a.i?a.i.card.Ie:a.Ie;
c&&d&&g.Fy(c,[d]);a.i=b;p4(a)}if(c="none"!=a.element.style.display)a.context.I.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Kt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&ATa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
ATa=function(a,b){a.X.xb?(b=new I3([0,
a.u.scrollTop],[0,b.uD.offsetTop],600,MSa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.kK(a.X,!0),a.u.scrollTop=b.uD.offsetTop,g.kK(a.X,!1))},q4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},tTa=function(a,b){return g.Ub(a.cards,function(c){return c.card.id===b})},r4=function(a,b,c){g4.call(this,a,b);
this.annotation=c;this.isActive=!1},DTa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},s4=function(a,b,c){r4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},ETa=function(a,b){var c=void 0===c?0:c;
var d=KSa(b).width;g.gn(b,d);c=new K3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,LSa);g.I(a,c);a.context.B.Ra(c,"begin",function(){g.qn(b,!0)});
c.play()},HTa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ja:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ja:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.FN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Da(d));var f=a.createElement({G:"div",Ja:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ja:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.qn(h,!1);var l=a.createElement({G:"div",Ja:["branding-context-container-outer"]});l.appendChild(h);g.$m(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){FTa(a,h,l)},500);
g.I(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){GTa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},GTa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.pn(b);a.i||(b.style.width=g.fn(f.width,!0),c.style.width=g.fn(f.width,!0));g.$m(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.$m(d,"right","1px");a.C=!0;g.qn(b,!0);a.D=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},FTa=function(a,b,c){g.ds(a.element,"iv-branding-active");
a.J=new g.L(function(){g.qn(b,!1);a.i||(c.style.width=g.fn(0,!0))},250);
a.J.start();a.C=!1},ITa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},t4=function(a,b,c){r4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ja:["iv-promo-contents"]});this.D=new g.L(function(){d.i.setAttribute("aria-hidden","true");g.qn(d.B,!1);g.qn(d.u,!0)},700,this);
g.I(this,this.D)},JTa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=kTa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ja:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&h4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.sg(f,$3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ja:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ja:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&h4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&h4(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ja:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.M(a.i,"iv-click-target"),e&&h4(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ja:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Ra(a.u,"click",function(r){u4(a,5E3,r)});
c.appendChild(a.u);g.qn(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.OS,a);a.context.i.Ra(a.element,"mouseout",a.NS,a);a.context.i.Ra(a.element,"touchend",function(r){u4(a,5E3,r)});
a.B=a.createElement({G:"button",Ja:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.JS:a.IS,a);c.appendChild(a.B);g.cs(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},u4=function(a,b,c){c.stopPropagation();
KTa(a);LTa(a,b);a.i.focus()},MTa=function(a){a.isCollapsed||a.S||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},KTa=function(a){a.D.stop();
a.isCollapsed&&(g.es(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.qn(a.u,!1),g.qn(a.B,!0))},LTa=function(a,b){a.C||(a.C=g.di(function(){v4(this);
MTa(this)},b,a))},v4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},NTa=function(a){this.I=a},vTa=function(a,b,c){b&&(c?w4(a,b.map(function(d){return g.Qr(d,c)})):w4(a,b))},w4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.yv(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},x4=function(a){g.CM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.J={};this.logger=new NTa(this.player);this.C=new g.HC(this);this.D=this.ul=null;this.events=new g.HC(this);this.K=this.i=null;this.X=[];g.I(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.FQ,this);this.subscribe("resize",this.BA,this);this.player.V().S.subscribe("vast_info_card_add",this.pN,this);g.I(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ja:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.pM(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ja:["ytp-iv-video-content"]});g.I(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Lq()&&this.load();var c=this.createElement({G:"style"});(g.Ug("HEAD")[0]||document.body).appendChild(c);g.xe(this,function(){g.lh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},OTa=function(a){a=a.createElement({G:"div",
Ja:["annotation","annotation-type-custom"]});g.qn(a,!1);return a},PTa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.kK(a.u,b);g.kK(a.B,b)},QTa=function(a,b,c){a.S=!0;
a.D=g.nu(b,c)},RTa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(RTa(a,e))}return c},UTa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.gu(h)&&h.responseXML?h.responseXML:null)&&y4(a,h)}};
g.Ku()&&(d.onFinish=STa(a,d.onFinish));d.postParams={ic_only:"1"};TTa(d,c);a.S=!0;g.nu(b.Va,d)}}},TTa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Zu&&(a.postParams.ic_coll=b.Zu);b.Jy&&(a.postParams.ic_xml=b.Jy);b.Lx&&(a.postParams.ic_track=b.Lx)},VTa=function(a){var b=new g.V({G:"div"});
g.qn(b.element,!1);var c=new l4(a.player,b.element,z4(a));g.I(c,b);b.Da(a.u.element);c.tx();return c},z4=function(a){if(!a.K){var b=new L3(a);
g.I(a,b);var c=new g.Gl(a);g.I(a,c);a.K=new ITa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.ge)}return a.K},y4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ny();if(e){var f=g.my();f&&g.Ay(void 0,e,f,[g.jy(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=RTa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Z3(f.type,WTa),p=Z3(f.style,XTa),r=bTa(f.data),t=0!==r.length?JSON.parse(r):{};var v=f.action;f=hTa;if(null==v)var x=null;else if(g.Ma(v)){l=[];for(var y=g.q(v),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}x=l}else{var H=f(v);x=H?[H]:[]}e=m&&n?new iTa(m,n,p,x,t):null}else e=null}catch(pa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=OTa(f),J=null;switch(l.type){case "branding":if(f.player.V().yb)break;f.u.element.appendChild(F);J=new s4(F,z4(f),l);break;case "promotion":g.pM(f.player,F,4),J=new t4(F,z4(f),l)}J&&J.tx();if(f=J)g.I(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=VTa(a),g.I(a,a.i));if("card"===e.type){c=a.i;var W=e&&e.data&&e.data.card_type;
f=e.data;if(W)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,zO:l.teaser_impression,xB:l.teaser_click},F=f.tracking_params||{},J=null,W){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Nl:F.card?g.jy(F.card):null,bj:F.teaser?g.jy(F.teaser):null,Ie:F.icon?g.jy(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:a4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};o4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Nl:F.card?g.jy(F.card):
null,bj:F.teaser?g.jy(F.teaser):null,Ie:F.icon?g.jy(F.icon):null,Ix:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:a4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};o4(c,e);break;case "productListing":f.signin_url&&(J=a4({target:"current",value:f.signin_url}));W=[];for(var Z=f.offers||[],K=0;K<Z.length;K++)W.push(new nTa(g.Hg(Z[K].merchant),g.Hg(Z[K].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Nl:F.card?g.jy(F.card):null,bj:F.teaser?g.jy(F.teaser):null,Ie:F.icon?g.jy(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,By:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:a4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),mea:J,lea:f.signin_title?f.signin_title:void 0,jea:f.signin_message?f.signin_message:void 0,offers:W};o4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Nl:F.card?g.jy(F.card):null,bj:F.teaser?g.jy(F.teaser):
null,Ie:F.icon?g.jy(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,By:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:a4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};o4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Nl:F.card?g.jy(F.card):null,bj:F.teaser?g.jy(F.teaser):null,Ie:F.icon?g.jy(F.icon):null,Ix:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:a4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},o4(c,e)}}else rTa(a.i,e);c=!0}}c&&(D3(a.player),a.BA())},YTa=function(a,b){var c=!1;
a.i||(a.i=VTa(a),g.I(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(sTa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.sz(b.headerText):"",g.th(c.jb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.jy(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.jy(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ie=b.icon.infoCardIconRenderer.trackingParams?
g.jy(b.icon.infoCardIconRenderer.trackingParams):null,D3(a.player),a.BA())},ZTa=function(a,b,c,d,e){if(!a.player.V().yb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new eTa("openUrl","click",new cTa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.sz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.sz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.sz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.sz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.sz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.sz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new iTa(c,"branding","branding",f,d);l=OTa(a);a.u.element.appendChild(l);f=new s4(l,z4(a),f);f.tx();g.I(f,f);a.J[c]=f}},STa=function(a,b){return function(){var c=g.Aa.apply(0,arguments);
a.isDisposed()||a.X.push(g.wv.Qf(function(){b.apply(null,g.u(c))}))}},$Ta=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.iM.prototype.Kt=g.ca(17,function(a,b){var c=g.RM(this.ub());c&&c.Kt(a,b)});
var F3={},G3=null;g.Ta(I3,g.ms);g.k=I3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Hc())return!1;H3(this);this.startTime=a=g.Sa();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.xA();this.zi("play");-1==this.i&&this.zi("resume");this.i=1;var b=g.Pa(this);b in F3||(F3[b]=this);OSa();PSa(this,a);return!0};
g.k.stop=function(a){H3(this);this.i=0;a&&(this.progress=1);QSa(this,this.progress);this.zi("stop");this.Nw()};
g.k.pause=function(){this.Hc()&&(H3(this),this.i=-1,this.zi("pause"))};
g.k.ya=function(){0==this.i||this.stop(!1);this.zi("destroy");I3.oe.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.vC=function(){this.zi("animate")};
g.k.zi=function(a){this.dispatchEvent(new RSa(a,this))};
g.Ta(RSa,g.ye);g.Ta(J3,I3);J3.prototype.C=g.Ia;J3.prototype.vC=function(){this.C();J3.oe.vC.call(this)};
J3.prototype.Nw=function(){this.C();J3.oe.Nw.call(this)};
J3.prototype.xA=function(){this.C();J3.oe.xA.call(this)};
g.Ta(K3,J3);K3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(L3,g.G);L3.prototype.Ra=function(a,b,c,d){c=(0,g.E)(c,d||this.u);a=g.hv(a,b,c);this.i.push(a);return a};
L3.prototype.fA=function(a,b,c,d){c=(0,g.E)(c,d||this.u);a=g.yja(a,b,c);this.i.push(a);return a};
L3.prototype.xc=function(a){g.iv(a);g.cc(this.i,a)};
L3.prototype.ya=function(){g.iv(this.i);this.i.length=0;g.G.prototype.ya.call(this)};g.w(P3,g.CM);g.k=P3.prototype;g.k.load=function(){g.CM.prototype.load.call(this);if(!Q3(this)){var a=g.gta(this.player.getVideoData());a?(a=O3(a,TSa(this)),R3(this,a,!1)):USa(this)}};
g.k.unload=function(){R3(this,null);this.B&&(this.B.abort(),this.B=null);g.CM.prototype.unload.call(this)};
g.k.nf=function(a,b){return Q3(this)?"loadCustomEndscreenRenderer"===a?(a=O3(b,"new"),R3(this,a),!0):null:null};
g.k.getOptions=function(){return Q3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.zb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<aUa.length;f++){var h=Math.abs(b.width-aUa[f]);if(-1===e||d>=h)e=f,d=h}d=bUa[e];this.u&&g.$m(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.on(e.element,Math.round(h.width*a.width),f);g.gn(e.element,m,n);g.es(e.element,cUa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.es(e.element,bUa);g.M(e.element,d);(e=g.Vg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.$m(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())Y3(this,this.endscreen.impressionUrls),(a=g.ny())&&this.endscreen.visualElement&&g.By(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");Y3(this,c.impressionUrls);(b=g.ny())&&g.By(b,c.visualElement,void 0);this.player.V().B&&this.player.Pa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.ds(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.ds(b,"ytp-ce-shown");this.player.V().B&&this.player.Pa("endscreenelementhidden",a)}};
g.k.fX=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.es(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var aUa=[346,426,470,506,570,640,853,1280,1920],bUa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),cUa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var dTa={A2:"current",B8:"new"};var fTa={CLOSE:"close",V8:"openUrl",SUBSCRIBE:"subscribe"},gTa={u_:"click",CLOSE:"close",Y3:"hidden",v$:"rollOut",w$:"rollOver",qaa:"shown"};var XTa={wZ:"anchored",qP:"branding",CHANNEL:"channel",z2:"cta",b4:"highlightText",p5:"label",PLAYLIST:"playlist",N9:"popup",zaa:"speech",SUBSCRIBE:"subscribe",Raa:"title",VIDEO:"video",xca:"website"},WTa={qP:"branding",h_:"card",Q2:"drawer",a4:"highlight",R6:"marker",X9:"promotion",TEXT:"text",bda:"widget"};g.w(g4,g.G);g.k=g4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.lz(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Va.set(a,e);this.context.I.Gd([a])};
g.k.tx=function(){this.context.u.subscribe("resize",this.Ey,this)};
g.k.wC=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.lh(this.element)};
g.k.Ey=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=$3(a);if(f){var h=pTa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.Zt(f||"");m&&n&&(n.v||n.list)?e.context.I.Xj(n.v,b,n.list,!1):g.tL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);w4(this.context.logger,c,l,d);oTa(f)||(c=g.ny(),d=b.itct,c&&d&&g.Gy(c,g.jy(d)))}};
g.k.ya=function(){this.Sa.clear();this.Va.clear();g.G.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.w(l4,g4);g.k=l4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.pn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Ey=function(){var a=this.isAvailable();g.qn(this.element,a);g.N(this.context.I.getRootNode(),g.kT.IV_DRAWER_ENABLED,a);D3(this.I)};
g.k.destroy=function(){this.I.Kt(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Fv(this.Z);g.iv(this.xa);this.La&&this.La.dispose();this.D&&this.D.dispose();g4.prototype.destroy.call(this)};
g.k.TR=function(){if(this.B){w4(this.context.logger,q4(this).tracking.close);var a=g.ny();a&&this.K&&g.Gy(a,this.K);k4(this)}};
g.k.fS=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.zT=function(){var a=g.ny(),b=q4(this);b=b?b.Ie:this.Ie;a&&b&&g.Ey(a,[b])};
g.k.yT=function(){var a=g.ny(),b=q4(this);b=b?b.Ie:this.Ie;a&&b&&g.Fy(a,[b])};
g.k.EQ=function(){var a=q4(this);w4(this.context.logger,a.tracking.zO);var b=g.ny();b&&a&&g.Ey(b,[a.bj,a.Ie])};
g.k.AT=function(){var a=g.ny(),b=q4(this);a&&b&&g.Fy(a,[b.bj])};
g.k.DQ=function(a){var b=q4(this),c=g.ny();this.i?a?(a=this.context.logger,w4(a,b.tracking.xB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.bj&&g.Gy(c,b.bj)):(a=this.context.logger,w4(a,b.tracking.xB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Ie&&g.Gy(c,b.Ie)):(a=this.context.logger,w4(a,b.tracking.xB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Ie&&g.Gy(c,this.Ie))};g.w(r4,g4);r4.prototype.tx=function(){g4.prototype.tx.call(this);DTa(this)};
r4.prototype.show=function(){g4.prototype.show.call(this);var a=g.ny(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ey(a,[g.jy(b.itct)])};
r4.prototype.hide=function(){g4.prototype.hide.call(this);var a=g.ny(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Fy(a,[g.jy(b.itct)])};g.w(s4,r4);
s4.prototype.show=function(){if(!this.isActive){r4.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ja:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.qn(this.u,!1);var b=this.createElement({G:"div",Ja:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=kTa(this.annotation))&&h4(this,this.u,b,this.annotation.id,
a.session_data);HTa(this,a);this.K=!0}g.qn(this.element,!0);this.isActive=!0;this.u&&ETa(this,this.u)}};
s4.prototype.hide=function(){this.isActive&&(r4.prototype.hide.call(this),g.qn(this.element,!1),this.isActive=!1)};
s4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);r4.prototype.destroy.call(this)};g.w(t4,r4);g.k=t4.prototype;g.k.show=function(){this.isActive||(r4.prototype.show.call(this),this.X||(JTa(this),this.X=!0),g.qn(this.element,!0),g.di(function(){g.ds(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,v4(this),KTa(this),LTa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.wC=function(a,b,c,d,e,f){return this.isCollapsed?!1:r4.prototype.wC.call(this,a,b,c,d,e,f)};
g.k.OS=function(a){this.S=!0;u4(this,500,a)};
g.k.NS=function(){this.S=!1;MTa(this)};
g.k.IS=function(a){a.stopPropagation();this.hide()};
g.k.JS=function(a){a.stopPropagation();v4(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();r4.prototype.destroy.call(this)};g.w(x4,g.CM);g.k=x4.prototype;g.k.nf=function(a,b){if(!$Ta(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.Z1(b))&&y4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(uTa(this.i,b),D3(this.player)),!0}return null};
g.k.getOptions=function(){return $Ta(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Lq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.LL||a.S.get(b.videoId)||g.fG(b)||g.gG(b)?!0:!1};
g.k.BA=function(){if(this.B){var a=this.player.eb().getVideoContentRect(!0);g.on(this.B.element,a.width,a.height);g.gn(this.B.element,a.left,a.top)}if(this.i){var b=this.player.zj();a=this.i;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.FQ=function(a){PTa(this,a.state);g.T(a.state,2)&&(this.Dh()&&this.Ck()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Kt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.gu(h)&&h.responseXML?h.responseXML:null)&&(y4(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.CM.prototype.load.call(this);PTa(this,this.player.Ab());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Ku()&&(a=STa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&TTa(e,f);f=f&&(f.Jy||f.Zu);if(!c.ip||f)c.Va?QTa(this,c.Va,e):(this.ul=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.ul));
g.pM(this.player,this.B.element,4);this.BA();(f=g.fG(c))&&YTa(this,f);(f=g.gG(c))&&f.featuredChannel&&ZTa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.ul&&(this.player.removeEventListener("videodatachange",this.ul),this.ul=null),QTa(this,b.Va,a))};
g.k.unload=function(){this.player.Ze("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,D3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.J={};this.u.hide();g.CM.prototype.unload.call(this);this.B.detach();this.ul&&(this.player.removeEventListener("videodatachange",this.ul),this.ul=null)};
g.k.pN=function(a){a===this.player.getVideoData().videoId&&(this.loaded?UTa(this):this.load())};
g.k.Dh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Ck=function(){this.Dh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Dh();this.i&&(a?c?j4(this.i,c,b):j4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):k4(this.i))};
g.k.Kt=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.pN,this);g.ds(this.player.getRootNode(),g.kT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.wv.wi(a[b]);this.X.length=0;g.CM.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.BM("annotations_module",x4);g.BM("creatorendscreen",P3);})(_yt_player);
