(function(g){var window=this;'use strict';var rWa=function(a,b){return g.Qe(a,b)},sWa=function(a,b){b=b instanceof g.Rf?b:g.ag(b,/^data:image\//i.test(b));
a.src=g.Sf(b)},Y6=function(a){g.Al(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},Z6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Fl(a.u,b,c)},tWa=function(a){if(a===g.Ip)throw Error("ES6 Iteration protocol does NOT adjust control flow when StopIteration is thrown from callback helper functions. If your code relies on this behavior, consider throwing a different error and catching it to terminate iteration.");
throw a;},uWa=function(a){if(a instanceof g.Gp)return a;
if("function"==typeof a.Mg)return a.Mg(!1);if(g.Ma(a)){var b=0,c=new g.Gp;c.next=function(){for(;;){if(b>=a.length)return g.k2;if(b in a)return g.Hp(a[b++]);b++}};
var d=c.next;c.Ij=function(){return g.Jp(d.call(c))};
return c}throw Error("Not implemented");},vWa=function(a,b,c){if(g.Ma(a))try{g.qc(a,b,c)}catch(e){tWa(e)}else for(a=uWa(a);;){var d=void 0;
try{d=a.Ij()}catch(e){if(e===g.Ip)break;throw e;}try{b.call(c,d,void 0,a)}catch(e){tWa(e)}}},wWa=function(a,b){var c=[];
vWa(b,function(d){try{var e=g.Cs.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Kfa(e)&&c.push(d)},a);
return c},xWa=function(a,b){wWa(a,b).forEach(function(c){g.Cs.prototype.remove.call(this,c)},a)},yWa=function(a){if(a.xa){if(a.xa.locationOverrideToken)return{locationOverrideToken:a.xa.locationOverrideToken};
if(null!=a.xa.latitudeE7&&null!=a.xa.longitudeE7)return{latitudeE7:a.xa.latitudeE7,longitudeE7:a.xa.longitudeE7}}return null},zWa=function(a,b){g.Zb(a,b)||a.push(b)},$6=function(a){var b=0,c;
for(c in a)b++;return b},AWa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},a7=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return AWa(a)},BWa=function(a,b,c,d){var e=new g.el(null,void 0);
a&&g.fl(e,a);b&&g.gl(e,b);c&&g.hl(e,c);d&&(e.K=d);return e},b7=function(a,b){g.Cv[a]=!0;
var c=g.Av();c&&c.publish.apply(c,arguments);g.Cv[a]=!1},c7=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.js;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",CWa(this,a.capabilities||""),DWa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},CWa=function(a,b){a.capabilities.clear();
g.iq(b.split(","),g.Ra(rWa,EWa)).forEach(function(c){a.capabilities.add(c)})},DWa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},d7=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},e7=function(a,b){return!!b&&(a.id==b||a.uuid==b)},FWa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},GWa=function(a){return new d7(a)},HWa=function(a){return Array.isArray(a)?g.Vn(a,GWa):[]},f7=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},g7=function(a){return Array.isArray(a)?"["+g.Vn(a,f7).join(",")+"]":"null"},h7=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},IWa=function(a){return g.Vn(a,function(b){return{key:b.id,
name:b.name}})},i7=function(a,b){return g.Ub(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},j7=function(a,b){return g.Ub(a,function(c){return e7(c,b)})},JWa=function(){var a=(0,g.Iy)();
a&&xWa(a,a.i.Mg(!0))},k7=function(){var a=g.Ly("yt-remote-connected-devices")||[];
g.nc(a);return a},KWa=function(a){if(g.$b(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Vn(a,function(d,e){return 0==e?d:d.substring(c.length)})},LWa=function(a){g.Ky("yt-remote-connected-devices",a,86400)},m7=function(){if(l7)return l7;
var a=g.Ly("yt-remote-device-id");a||(a=h7(),g.Ky("yt-remote-device-id",a,31536E3));for(var b=k7(),c=1,d=a;g.Zb(b,d);)c++,d=a+"#"+c;return l7=d},n7=function(){var a=k7(),b=m7();
g.Zb(a,b);g.Ny()&&g.pc(a,b);a=KWa(a);if(g.$b(a))try{g.cja("remote_sid")}catch(c){}else try{g.Du("remote_sid",a.join(","),-1)}catch(c){}},MWa=function(){return g.Ly("yt-remote-session-browser-channel")},NWa=function(){return g.Ly("yt-remote-local-screens")||[]},OWa=function(){g.Ky("yt-remote-lounge-token-expiration",!0,86400)},PWa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Vn(NWa(),function(d){return d.loungeToken}),c=g.Vn(a,function(d){return d.loungeToken});
g.Wn(c,function(d){return!g.Zb(b,d)})&&OWa();
g.Ky("yt-remote-local-screens",a,31536E3)},QWa=function(a,b){g.Ky("yt-remote-session-browser-channel",a);
g.Ky("yt-remote-session-screen-id",b);a=k7();b=m7();g.Zb(a,b)||a.push(b);LWa(a);n7()},o7=function(a){a||(g.My("yt-remote-session-screen-id"),g.My("yt-remote-session-video-id"));
n7();a=k7();g.cc(a,m7());LWa(a)},RWa=function(){if(!p7){var a=g.Ls();
a&&(p7=new g.zs(a))}},SWa=function(){RWa();
return p7?!!p7.get("yt-remote-use-staging-server"):!1},q7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},TWa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},UWa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r7=function(a){a.length?VWa(a.shift(),function(){r7(a)}):s7()},WWa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},VWa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.zk(d,g.os(a));(document.head||document.documentElement).appendChild(d)},XWa=function(){var a=q7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},s7=function(){var a=UWa();
a&&a(!1,"No cast extension found")},t7=function(){if(YWa){var a=2,b=UWa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;VWa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s7,c)}},ZWa=function(){t7();
var a=XWa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},aXa=function(){t7();
var a=XWa();a.push.apply(a,g.u($Wa.map(WWa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");r7(a)},u7=function(a,b,c){g.G.call(this);
this.J=null!=c?(0,g.E)(a,c):a;this.Xf=b;this.D=(0,g.E)(this.ZQ,this);this.i=!1;this.u=0;this.B=this.Nb=null;this.C=[]},v7=function(a,b,c){g.G.call(this);
this.C=null!=c?a.bind(c):a;this.Xf=b;this.B=null;this.i=!1;this.u=0;this.Nb=null},w7=function(a){a.Nb=g.di(function(){a.Nb=null;
a.i&&!a.u&&(a.i=!1,w7(a))},a.Xf);
var b=a.B;a.B=null;a.C.apply(null,b)},x7=function(){},y7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},A7=function(a){z7.dispatchEvent(new bXa(z7,a))},bXa=function(a,b){g.ye.call(this,"statevent",a);
this.stat=b},B7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.Gl(this);this.J=new g.ci;this.J.setInterval(250)},dXa=function(a,b,c){a.Vt=1;
a.fn=Y6(b.clone());a.Cq=c;a.D=!0;cXa(a,null)},C7=function(a,b,c,d,e){a.Vt=1;
a.fn=Y6(b.clone());a.Cq=null;a.D=c;e&&(a.eO=!1);cXa(a,d)},cXa=function(a,b){a.Ht=Date.now();
D7(a);a.Oo=a.fn.clone();Z6(a.Oo,"t",a.K);a.MB=0;a.Mf=a.i.KD(a.i.zx()?b:null);0<a.zC&&(a.bB=new v7((0,g.E)(a.iP,a,a.Mf),a.zC));a.C.Ra(a.Mf,"readystatechange",a.aR);b=a.gp?g.Xe(a.gp):{};a.Cq?(a.KB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Mf.send(a.Oo,a.KB,a.Cq,b)):(a.KB="GET",a.eO&&!g.ch&&(b.Connection="close"),a.Mf.send(a.Oo,a.KB,null,b));a.i.Jj(1)},fXa=function(a,b){var c=a.MB,d=b.indexOf("\n",c);
if(-1==d)return E7;c=Number(b.substring(c,d));if(isNaN(c))return eXa;d+=1;if(d+c>b.length)return E7;b=b.substr(d,c);a.MB=d+c;return b},hXa=function(a,b){a.Ht=Date.now();
D7(a);var c=b?window.location.hostname:"";a.Oo=a.fn.clone();g.Al(a.Oo,"DOMAIN",c);g.Al(a.Oo,"t",a.K);try{a.Vj=new ActiveXObject("htmlfile")}catch(m){F7(a);a.Wm=7;A7(22);G7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in H7)f=H7[f];else if(f in gXa)f=H7[f]=gXa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
H7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.pg(g.Jf("b/12014412"),d);a.Vj.open();a.Vj.write(g.lg(c));a.Vj.close();a.Vj.parentWindow.m=(0,g.E)(a.VW,a);a.Vj.parentWindow.d=(0,g.E)(a.oN,a,!0);a.Vj.parentWindow.rpcClose=(0,g.E)(a.oN,a,!1);c=a.Vj.createElement("DIV");a.Vj.parentWindow.document.body.appendChild(c);d=g.$f(a.Oo.toString());d=g.Gg(g.Sf(d));d=g.pg(g.Jf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.rg(c,d);a.i.Jj(1)},D7=function(a){a.DH=Date.now()+
a.u;
iXa(a,a.u)},iXa=function(a,b){if(null!=a.pu)throw Error("WatchDog timer not null");
a.pu=y7((0,g.E)(a.cX,a),b)},I7=function(a){a.pu&&(g.C.clearTimeout(a.pu),a.pu=null)},G7=function(a){a.i.vf()||a.Ap||a.i.qy(a)},F7=function(a){I7(a);
g.ve(a.bB);a.bB=null;a.J.stop();g.Il(a.C);if(a.Mf){var b=a.Mf;a.Mf=null;b.abort();b.dispose()}a.Vj&&(a.Vj=null)},J7=function(a,b){try{a.i.hN(a,b),a.i.Jj(4)}catch(c){}},kXa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;jXa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){kXa(a,b,c,d,f)},f)})}},jXa=function(a,b,c){var d=new Image;
d.onload=function(){try{K7(d),c(!0)}catch(e){}};
d.onerror=function(){try{K7(d),c(!1)}catch(e){}};
d.onabort=function(){try{K7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
sWa(d,a)},K7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},lXa=function(a){this.i=a;
this.u=new x7},mXa=function(a){var b=L7(a.i,a.Wu,"/mail/images/cleardot.gif");
Y6(b);kXa(b.toString(),5E3,(0,g.E)(a.MR,a),3,2E3);a.Jj(1)},N7=function(a){var b=a.i.X;
if(null!=b)A7(5),b?(A7(11),M7(a.i,a,!1)):(A7(12),M7(a.i,a,!0));else if(a.qh=new B7(a,void 0,void 0,void 0),a.qh.gp=a.AC,b=a.i,b=L7(b,b.zx()?a.Nu:null,a.BC),A7(5),!g.Gc||g.zc(10))Z6(b,"TYPE","xmlhttp"),C7(a.qh,b,!1,a.Nu,!1);else{Z6(b,"TYPE","html");var c=a.qh;a=!!a.Nu;c.Vt=3;c.fn=Y6(b.clone());hXa(c,a)}},O7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new x7;this.S=a||null;this.X=null!=b?b:null;this.J=c||!1},nXa=function(a,b){this.i=a;
this.map=b;this.context=null},oXa=function(a,b,c,d){g.ye.call(this,"timingevent",a);
this.size=b;this.mx=d},pXa=function(a){g.ye.call(this,"serverreachability",a)},sXa=function(a){qXa(a);
if(3==a.i){var b=a.Cw++,c=a.gz.clone();g.Al(c,"SID",a.B);g.Al(c,"RID",b);g.Al(c,"TYPE","terminate");P7(a,c);b=new B7(a,a.B,b,void 0);b.Vt=2;b.fn=Y6(c.clone());sWa(new Image,b.fn.toString());b.Ht=Date.now();D7(b)}rXa(a)},tXa=function(a){a.lS(1,0);
a.gz=L7(a,null,a.CC);Q7(a)},qXa=function(a){a.qn&&(a.qn.abort(),a.qn=null);
a.Me&&(a.Me.cancel(),a.Me=null);a.Ll&&(g.C.clearTimeout(a.Ll),a.Ll=null);R7(a);a.Wg&&(a.Wg.cancel(),a.Wg=null);a.Fn&&(g.C.clearTimeout(a.Fn),a.Fn=null)},uXa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new nXa(a.UT++,b));2!=a.i&&3!=a.i||Q7(a)},vXa=function(a){var b=0;
a.Me&&b++;a.Wg&&b++;return b},Q7=function(a){a.Wg||a.Fn||(a.Fn=y7((0,g.E)(a.mN,a),0),a.Cs=0)},xXa=function(a,b){if(1==a.i){if(!b){a.Cw=Math.floor(1E5*Math.random());
b=a.Cw++;var c=new B7(a,"",b,void 0);c.gp=a.lk;var d=S7(a),e=a.gz.clone();g.Al(e,"RID",b);g.Al(e,"CVER","1");P7(a,e);dXa(c,e,d);a.Wg=c;a.i=2}}else 3==a.i&&(b?wXa(a,b):0==a.u.length||a.Wg||wXa(a))},wXa=function(a,b){if(b)if(6<a.Bp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Cw-1;b=S7(a)}else c=b.S,b=b.Cq;else c=a.Cw++,b=S7(a);var d=a.gz.clone();g.Al(d,"SID",a.B);g.Al(d,"RID",c);g.Al(d,"AID",a.Xs);P7(a,d);c=new B7(a,a.B,c,a.Cs+1);c.gp=a.lk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wg=c;dXa(c,d,b)},P7=function(a,b){a.Nf&&(a=a.Nf.HK())&&g.Ge(a,function(c,d){g.Al(b,d,c)})},S7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Bp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={gr:e.gr},f++){e.gr=a.u[f].i;var h=a.u[f].map;e.gr=6>=a.Bp?f:e.gr-d;try{g.Ge(h,function(l){return function(m,n){c.push("req"+l.gr+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.gr+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},yXa=function(a){a.Me||a.Ll||(a.K=1,a.Ll=y7((0,g.E)(a.lN,a),0),a.Wr=0)},T7=function(a){if(a.Me||a.Ll||3<=a.Wr)return!1;
a.K++;a.Ll=y7((0,g.E)(a.lN,a),zXa(a,a.Wr));a.Wr++;return!0},M7=function(a,b,c){a.IB=c;
a.nk=b.Bl;a.J||tXa(a)},R7=function(a){null!=a.Jp&&(g.C.clearTimeout(a.Jp),a.Jp=null)},zXa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U7=function(a,b){if(2==b||9==b){var c=null;
a.Nf&&(c=null);var d=(0,g.E)(a.fY,a);c||(c=new g.el("//www.google.com/images/cleardot.gif"),Y6(c));jXa(c.toString(),1E4,d)}else A7(2);AXa(a,b)},AXa=function(a,b){a.i=0;
a.Nf&&a.Nf.UJ(b);rXa(a);qXa(a)},rXa=function(a){a.i=0;
a.nk=-1;if(a.Nf)if(0==a.C.length&&0==a.u.length)a.Nf.wD();else{g.fc(a.C);var b=g.fc(a.u);a.C.length=0;a.u.length=0;a.Nf.wD(b)}},L7=function(a,b,c){var d=g.Bl(c);
if(""!=d.i)b&&g.gl(d,b+"."+d.i),g.hl(d,d.B);else{var e=window.location;d=BWa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dv&&g.Ge(a.Dv,function(f,h){g.Al(d,h,f)});
g.Al(d,"VER",a.Bp);P7(a,d);return d},BXa=function(){},CXa=function(){this.i=[];
this.u=[]},DXa=function(a,b){this.action=a;
this.params=b||{}},V7=function(a,b){g.G.call(this);
this.i=new g.L(this.MW,0,this);g.I(this,this.i);this.Xf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.E)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.E)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},W7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.xa=a;this.J=b;this.B=new g.ys;this.u=new V7(this.HX,this);this.i=null;this.Z=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.oa=d;this.Ba=e},EXa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.IB,sessionId:a.i.B,arrayId:a.i.Xs}},FXa=function(a,b){a.S=b||0;
a.u.stop();X7(a);a.i&&(3==a.i.getState()&&xXa(a.i),sXa(a.i));a.S=0},Y7=function(a){return!!a.i&&3==a.i.getState()},X7=function(a){if(a.i){var b=a.oa(),c=a.i.lk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.lk=c}},Z7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Vi(4,a))||"";b&&(this.port=":"+b);this.domain=g.Wi(a)||"";a=g.wb();0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.vb(a,"10.0")&&(this.u=!1))},$7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.gj(c+b,{})},a8=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.C,d,!0),onError:g.Ra(a.B,e),onTimeout:g.Ra(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.nu(b,a)},JXa=function(){var a=GXa;
HXa();b8.push(a);IXa()},c8=function(a,b){HXa();
var c=KXa(a,String(b));g.$b(b8)?LXa(c):(IXa(),g.qc(b8,function(d){d(c)}))},HXa=function(){b8||(b8=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",b8,void 0))},LXa=function(a){var b=(d8+1)%50;
d8=b;e8[b]=a;f8||(f8=49==b)},IXa=function(){var a=b8;
if(e8[0]){var b=f8?d8:-1;do{b=(b+1)%50;var c=e8[b];g.qc(a,function(d){d(c)})}while(b!=d8);
e8=Array(50);d8=-1;f8=!1}},KXa=function(a,b){var c=(Date.now()-MXa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g8=function(a){g.Xx.call(this);
this.J=a;this.screens=[]},NXa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},OXa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.iq(a.screens,function(f){return!!i7(b,f)});
for(var d=0,e=b.length;d<e;d++)c=NXa(a,b[d])||c;return c},PXa=function(a,b){var c=a.screens.length;
a.screens=g.iq(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},h8=function(a,b,c,d,e){g.Xx.call(this);
this.B=a;this.K=b;this.C=c;this.J=d;this.D=e;this.u=0;this.i=null;this.Nb=NaN},j8=function(a){g8.call(this,"LocalScreenService");
this.u=a;this.i=NaN;i8(this);this.info("Initializing with "+g7(this.screens))},QXa=function(a){if(a.screens.length){var b=g.Vn(a.screens,function(d){return d.id}),c=$7(a.u,"/pairing/get_lounge_token_batch");
a8(a.u,c,{screen_ids:b.join(",")},(0,g.E)(a.MS,a),(0,g.E)(a.LS,a))}},i8=function(a){if(g.P("deprecate_pair_servlet_enabled"))return OXa(a,[]);
var b=HWa(NWa());b=g.iq(b,function(c){return!c.uuid});
return OXa(a,b)},k8=function(a,b){PWa(g.Vn(a.screens,FWa));
b&&OWa()},m8=function(a,b){g.Xx.call(this);
this.J=b;b=(b=g.Ly("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.J(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.Zb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;l8("Initialized with "+g.Mi(this.i))},n8=function(a,b,c){var d=$7(a.D,"/pairing/get_screen_availability");
a8(a.D,d,{lounge_token:b.token},(0,g.E)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.E)(function(){c(!1)},a))},o8=function(a,b){a:if($6(b)!=$6(a.i))var c=!1;
else{c=g.Oe(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(l8("Updated online screens: "+g.Mi(a.i)),a.i=b,a.ea("screenChange"));RXa(a)},p8=function(a){isNaN(a.B)||g.ju(a.B);
a.B=g.hu((0,g.E)(a.uG,a),0<a.C&&a.C<g.Sa()?2E4:1E4)},l8=function(a){c8("OnlineScreenService",a)},SXa=function(a){var b={};
g.qc(a.J(),function(c){c.token?b[c.token]=c.id:this.pe("Requesting availability of screen w/o lounge token.")});
return b},RXa=function(a){a=g.Oe(g.He(a.i,function(b){return b}));
g.nc(a);a.length?g.Ky("yt-remote-online-screen-ids",a.join(","),60):g.My("yt-remote-online-screen-ids")},q8=function(a,b){b=void 0===b?!1:b;
g8.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};TXa(this)},VXa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Gh(),l=c?j7(h,c):null;c&&(a.K||l)||(l=j7(h,b));if(l){l.uuid=b;var m=r8(a,l);n8(a.i,m,function(n){e(n?m:null)})}else c?UXa(a,c,(0,g.E)(function(n){var p=r8(this,new d7({name:d,
screenId:c,loungeToken:n,dialId:b||""}));n8(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},WXa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},XXa=function(a,b,c){n8(a.i,b,c)},UXa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.nu($7(a.C,"/pairing/get_lounge_token_batch"),e)},YXa=function(a){a.screens=a.u.Gh();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+g7(a.screens))},TXa=function(a){s8(a);
a.u=new j8(a.C);a.u.subscribe("screenChange",(0,g.E)(a.WS,a));YXa(a);a.K||(a.B=HWa(g.Ly("yt-remote-automatic-screen-cache")||[]));s8(a);a.info("Initializing automatic screens: "+g7(a.B));a.i=new m8(a.C,(0,g.E)(a.Gh,a,!0));a.i.subscribe("screenChange",(0,g.E)(function(){this.ea("onlineScreenChange")},a))},r8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=j7(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||ZXa(a));s8(a);a.D[b.uuid]=b.id;g.Ky("yt-remote-device-id-map",a.D,31536E3);return b},ZXa=function(a){a=g.iq(a.B,function(b){return"shortLived"!=b.idType});
g.Ky("yt-remote-automatic-screen-cache",g.Vn(a,FWa))},s8=function(a){a.D=g.Ly("yt-remote-device-id-map")||{}},t8=function(a,b,c){g.Xx.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},u8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},$Xa=function(a,b){a.C&&(a.C.token=b,r8(a.B,a.C));
a.ea("sessionScreen",a.C)},v8=function(a,b){c8(a.Ba,b)},w8=function(a,b,c){t8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.oa=(0,g.E)(this.fR,this);this.Aa=(0,g.E)(this.gX,this);this.Z=g.hu(function(){aYa(d,null)},12E4);
this.K=this.D=this.J=this.S=0;this.xa=!1;this.X="unknown"},x8=function(a,b){g.ju(a.K);
a.K=0;0==b?bYa(a):a.K=g.hu(function(){bYa(a)},b)},bYa=function(a){cYa(a,"getLoungeToken");
g.ju(a.D);a.D=g.hu(function(){dYa(a,null)},3E4)},cYa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Mi(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.E)(function(){v8(this,"Failed to send message: "+b+".")},a)):v8(a,"Sending yt message without session: "+g.Mi(c))},y8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.UK(b,function(c){u8(a,c)},function(){return a.Ag()},5)):a.Ag(Error("Waiting for session status timed out."))},fYa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);eYa(a,d,function(e){e?(a.xa=!0,r8(a.B,d),u8(a,d),a.X="unknown",x8(a,c)):(g.St(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Ag())},5)},aYa=function(a,b){g.ju(a.Z);
a.Z=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?fYa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.St(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),y8(a,b.screenId))):(g.St(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),y8(a,b.screenId)):y8(a,b.screenId):a.Ag(Error("Waiting for session status timed out."))},dYa=function(a,b){g.ju(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,x8(a,3E4)):($Xa(a,b.loungeToken),a.xa=!1,a.X="unknown",x8(a,b.loungeTokenRefreshIntervalMs))},eYa=function(a,b,c,d){g.ju(a.J);
a.J=0;XXa(a.B,b,function(e){e||0>d?c(e):a.J=g.hu(function(){eYa(a,b,c,d-1)},300)})},gYa=function(a){g.ju(a.S);
a.S=0;g.ju(a.J);a.J=0;g.ju(a.Z);a.Z=0;g.ju(a.D);a.D=0;g.ju(a.K);a.K=0},z8=function(a,b,c,d){t8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.La=c;this.Ka=null;this.Z=g.Ia;this.X=NaN;this.Ia=(0,g.E)(this.gR,this);this.D=g.Ia;this.K=this.J=0;this.oa=!1;this.xa="unknown"},A8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},hYa=function(a){a.D=a.B.HI(a.Aa,a.i.label,a.i.friendlyName,A8(a),function(b,c){a.D=g.Ia;
a.oa=!0;u8(a,b);"shortLived"==b.idType&&0<c&&B8(a,c)},function(b){a.D=g.Ia;
a.Ag(b)})},iYa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.La;SWa()&&(b.env_useStageMdx=1);return g.ej(b)},C8=function(a){return new Promise(function(b){a.Aa=h7();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,iYa(a));b(c);hYa(a)}else a.Z=function(){g.ju(a.X);a.Z=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,iYa(a));b(d);hYa(a)},a.X=g.hu(function(){a.Z()},100)})},kYa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new d7(b);return(new Promise(function(e){jYa(a,d,function(f){f?(a.oa=!0,r8(a.B,d),u8(a,d),B8(a,c)):g.St(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):C8(a)})},lYa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){VXa(a.B,c,b,d,function(f){f&&f.token&&u8(a,f);e(f)},function(f){v8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):C8(a)})},jYa=function(a,b,c,d){g.ju(a.J);
a.J=0;XXa(a.B,b,function(e){e||0>d?c(e):a.J=g.hu(function(){jYa(a,b,c,d-1)},300)})},B8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
A8(a)&&(g.ju(a.K),a.K=0,0==b?mYa(a):a.K=g.hu(function(){mYa(a)},b))},mYa=function(a){A8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.xa=c,B8(a,3E4)):(a.oa=!1,a.xa="unknown",$Xa(a,b.loungeToken),B8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.xa="noLoungeTokenResponse";B8(a,3E4)})},nYa=function(a){g.ju(a.J);
a.J=0;g.ju(a.K);a.K=0;a.D();a.D=function(){};
g.ju(a.X)},D8=function(a,b){t8.call(this,a,b,"ManualSession");
this.u=g.hu((0,g.E)(this.Ys,this,null),150)},E8=function(a,b){g.Xx.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.J=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.E)(this.YV,this)},oYa=function(a,b){return b?g.Ub(a.B,function(c){return e7(b,c.label)},a):null},F8=function(a){c8("Controller",a)},GXa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G8=function(a){return a.K||!!a.B.length||!!a.i},H8=function(a,b,c){b!=a.i&&(g.ve(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.E)(a.kN,a,b)),b.subscribe("sessionFailed",function(){return pYa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Ys(null)):a.ea("yt-remote-cast2-session-change",null))},pYa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},qYa=function(a){var b=a.u.GI(),c=a.i&&a.i.i;
a=g.Vn(b,function(d){c&&e7(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=oYa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},vYa=function(a,b,c,d){d.disableCastApi?I8("Cannot initialize because disabled by Mdx config."):rYa()?sYa(b,d)&&(J8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?tYa(a,c):(window.__onGCastApiAvailable=function(e,f){e?tYa(a,c):(K8("Failed to load cast API: "+f),L8(!1),J8(!1),g.My("yt-remote-cast-available"),g.My("yt-remote-cast-receiver"),
uYa(),c(!1))},d.loadCastApiSetupScript?g.Oy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=q7()&&ZWa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s7():89<=q7()?aXa():(t7(),r7($Wa.map(WWa))))):I8("Cannot initialize because not running Chrome")},uYa=function(){I8("dispose");
var a=M8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);wYa(!1);g.Fv(N8);N8.length=0},O8=function(){return!!g.Ly("yt-remote-cast-installed")},xYa=function(){var a=g.Ly("yt-remote-cast-receiver");
return a?a.friendlyName:null},yYa=function(){I8("clearCurrentReceiver");
g.My("yt-remote-cast-receiver")},zYa=function(){return O8()?M8()?M8().getCastSession():(K8("getCastSelector: Cast is not initialized."),null):(K8("getCastSelector: Cast API is not installed!"),null)},Q8=function(){O8()?M8()?P8()?(I8("Requesting cast selector."),M8().requestSession()):(I8("Wait for cast API to be ready to request the session."),N8.push(g.Ev("yt-remote-cast2-api-ready",Q8))):K8("requestCastSelector: Cast is not initialized."):K8("requestCastSelector: Cast API is not installed!")},R8=
function(a,b){P8()?M8().setConnectedScreenStatus(a,b):K8("setConnectedScreenStatus called before ready.")},rYa=function(){var a=0<=g.wb().search(/ (CrMo|Chrome|CriOS)\//);
return g.jA||a},AYa=function(a,b){M8().init(a,b)},sYa=function(a,b){var c=!1;
M8()||(a=new E8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Ky("yt-remote-cast-available",d);b7("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){I8("onReceiverSelected: "+d.friendlyName);
g.Ky("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){I8("onReceiverResumed: "+d.friendlyName);
g.Ky("yt-remote-cast-receiver",d);b7("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){I8("onSessionChange: "+f7(d));
d||g.My("yt-remote-cast-receiver");b7("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
I8("cloudview.createSingleton_: "+c);return c},M8=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},tYa=function(a,b){L8(!0);
J8(!1);AYa(a,function(c){c?(wYa(!0),g.Gv("yt-remote-cast2-api-ready")):(K8("Failed to initialize cast API."),L8(!1),g.My("yt-remote-cast-available"),g.My("yt-remote-cast-receiver"),uYa());b(c)})},I8=function(a){c8("cloudview",a)},K8=function(a){c8("cloudview",a)},L8=function(a){I8("setCastInstalled_ "+a);
g.Ky("yt-remote-cast-installed",a)},P8=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},wYa=function(a){I8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},S8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.K=0;this.trackData=null;this.hasNext=this.Pk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},T8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Pk=!1;a.hasNext=!1;a.K=0;a.J=g.Sa();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},U8=function(a){return a.Hc()?(g.Sa()-a.J)/1E3:0},V8=function(a,b){a.K=b;
a.J=g.Sa()},W8=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.J)/1E3+a.K;
case -1E3:return 0}return a.K},X8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T8(a)},Y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ye(a.trackData);b.hasPrevious=a.Pk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},$8=function(a,b){g.Xx.call(this);
this.B=0;this.C=a;this.J=[];this.D=new CXa;this.u=this.i=null;this.X=(0,g.E)(this.GU,this);this.K=(0,g.E)(this.Lw,this);this.S=(0,g.E)(this.FU,this);this.Z=(0,g.E)(this.NU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.KG,this),BYa(this))):c=3;0!=c&&(b?this.KG(c):g.hu((0,g.E)(function(){this.KG(c)},this),0));
(a=zYa())&&Z8(this,a);this.subscribe("yt-remote-cast2-session-change",this.Z)},a9=function(a){return new S8(a.C.getPlayerContextData())},BYa=function(a){g.qc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.J.push(this.C.subscribe(b,g.Ra(this.WV,b),this))},a)},CYa=function(a){g.qc(a.J,function(b){this.C.unsubscribeByKey(b)},a);
a.J.length=0},b9=function(a){return 1==a.getState()},c9=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},e9=function(a,b,c){var d=a9(a);
V8(d,c);-1E3!=d.playerState&&(d.playerState=b);d9(a,d)},f9=function(a,b,c){a.C.sendMessage(b,c)},d9=function(a,b){CYa(a);
a.C.setPlayerContextData(Y8(b));BYa(a)},Z8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Lw(null));
a.u=b;a.u&&(c8("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Lw(a.u.media[0]))},DYa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=a9(a);b.contentId!=d.videoId&&c8("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V8(d,a.i.getEstimatedTime());d9(a,d)}else c8("CP","No cast media video. Ignoring state update.")},g9=function(a,b,c){return(0,g.E)(function(d){this.pe("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pe("Retrying "+b+" using MDx browser channel."),f9(this,b,c))},a)},h9=function(a,b,c,d){d=void 0===d?!1:d;
g.Xx.call(this);this.D=NaN;this.xa=!1;this.S=this.K=this.Z=this.oa=NaN;this.X=[];this.C=this.J=this.B=this.wc=this.i=null;this.Ia=a;this.Ba=d;this.X.push(g.hv(window,"beforeunload",(0,g.E)(this.HS,this)));this.u=[];this.wc=new S8;this.Ka=b.id;this.Aa=b.idType;this.i=EYa(this,c);this.i.subscribe("handlerOpened",this.KU,this);this.i.subscribe("handlerClosed",this.HU,this);this.i.subscribe("handlerError",this.IU,this);this.i.subscribe("handlerMessage",this.JU,this);this.i.nB(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.wc.videoId;g.Ny()&&g.Ky("yt-remote-session-video-id",e)},this)},FYa=function(a){return g.Ub(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},i9=function(a){c8("conn",a)},EYa=function(a,b){return new W7($7(a.Ia,"/bc"),b,!1,function(){return a.LI()},"shortLived"==a.Aa)},j9=function(a,b){a.ea("proxyStateChange",b)},GYa=function(a){a.D=g.hu((0,g.E)(function(){i9("Connecting timeout");
this.ys(1)},a),2E4)},k9=function(a){g.ju(a.D);
a.D=NaN},l9=function(a){g.ju(a.oa);
a.oa=NaN},HYa=function(a){m9(a);
a.Z=g.hu((0,g.E)(function(){n9(this,"getNowPlaying")},a),2E4)},m9=function(a){g.ju(a.Z);
a.Z=NaN},JYa=function(a,b){var c=null;
if(b){var d=FYa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Ga("yt.mdx.remote.remoteClient_",c,void 0);b&&(k9(a),l9(a));c=Y7(a.i)&&isNaN(a.D);b==c?b&&(j9(a,1),n9(a,"getSubtitlesTrack")):b?(a.TK()&&a.wc.reset(),j9(a,1),n9(a,"getNowPlaying"),IYa(a)):a.ys(1)},KYa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.wc.videoId&&(g.Te(b.params)?a.wc.trackData=null:a.wc.trackData=b.params,a.ea("remotePlayerChange"))},LYa=function(a,b,c){var d=b.params.videoId||b.params.video_id,e=parseInt(b.params.currentIndex,10);
a.wc.listId=b.params.listId||a.wc.listId;X8(a.wc,d,e);a.ea("remoteQueueChange",c)},NYa=function(a,b){b.params=b.params||{};
LYa(a,b,"NOW_PLAYING_MAY_CHANGE");MYa(a,b);a.ea("autoplayDismissed")},MYa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V8(a.wc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.wc.playerState&&(c=-1E3);a.wc.playerState=c;c=Number(b.params.loadedTime);a.wc.S=isNaN(c)?0:c;a.wc.Rj(Number(b.params.duration));c=a.wc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.wc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.wc.playerState?HYa(a):m9(a);a.ea("remotePlayerChange")},OYa=function(a,b){if(-1E3!=a.wc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.wc.playerState=c;b=parseInt(b.params.currentTime,10);V8(a.wc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},PYa=function(a,b){var c="true"==b.params.muted;
a.wc.volume=parseInt(b.params.volume,10);a.wc.muted=c;a.ea("remotePlayerChange")},QYa=function(a,b){a.J=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},RYa=function(a,b){var c="true"==b.params.hasNext;
a.wc.Pk="true"==b.params.hasPrevious;a.wc.hasNext=c;a.ea("previousNextChange")},IYa=function(a){g.ju(a.S);
a.S=g.hu((0,g.E)(a.ys,a,1),864E5)},n9=function(a,b,c){c?i9("Sending: action="+b+", params="+g.Mi(c)):i9("Sending: action="+b);
a.i.sendMessage(b,c)},o9=function(a){g8.call(this,"ScreenServiceProxy");
this.Ue=a;this.i=[];this.i.push(this.Ue.$_s("screenChange",(0,g.E)(this.DP,this)));this.i.push(this.Ue.$_s("onlineScreenChange",(0,g.E)(this.CV,this)))},VYa=function(a,b){RWa();
if(!p7||!p7.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;JWa();n7();p9||(p9=new Z7(b?b.loungeApiHost:void 0),SWa()&&(p9.i="/api/loungedev"));q9||(q9=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",q9,void 0));SYa();var c=r9();if(!c){var d=new q8(p9,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=r9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Ga("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);vYa(a,d,function(f){f?s9()&&R8(s9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){b7("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),t9("Initializing: "+
g.Mi(b)),u9.push(g.Ev("yt-remote-cast2-api-ready",function(){b7("yt-remote-api-ready")})),u9.push(g.Ev("yt-remote-cast2-availability-change",function(){b7("yt-remote-receiver-availability-change")})),u9.push(g.Ev("yt-remote-cast2-receiver-selected",function(){v9(null);
b7("yt-remote-auto-connect","cast-selector-receiver")})),u9.push(g.Ev("yt-remote-cast2-receiver-resumed",function(){b7("yt-remote-receiver-resumed","cast-selector-receiver")})),u9.push(g.Ev("yt-remote-cast2-session-change",TYa)),u9.push(g.Ev("yt-remote-connection-change",function(f){f?R8(s9(),"YouTube TV"):w9()||(R8(null,null),yYa())})),u9.push(g.Ev("yt-remote-cast2-session-failed",function(){b7("yt-remote-connection-failed")})),a=x9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.P("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),t9(" -- with channel params: "+g.Mi(a)),a?(g.Ky("yt-remote-session-app",a.app),g.Ky("yt-remote-session-name",a.name)):(g.My("yt-remote-session-app"),g.My("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),s9()||UYa())}},WYa=function(){var a=r9().Ue.$_gos();
var b=y9();b&&z9()&&(i7(a,b)||a.push(b));return IWa(a)},A9=function(){var a=XYa();
!a&&O8()&&xYa()&&(a={key:"cast-selector-receiver",name:xYa()});return a},XYa=function(){var a=WYa(),b=y9();
b||(b=w9());return g.Ub(a,function(c){return b&&e7(b,c.key)?!0:!1})},y9=function(){var a=s9();
if(!a)return null;var b=r9().Gh();return j7(b,a)},TYa=function(a){t9("remote.onCastSessionChange_: "+f7(a));
if(a){var b=y9();if(b&&b.id==a.id){if(R8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))B9&&(B9.token=a),(b=z9())&&b.nB(a)}else b&&C9(),D9(a,1)}else z9()&&C9()},C9=function(){P8()?M8().stopSession():K8("stopSession called before API ready.");
var a=z9();a&&(a.disconnect(1),E9(null))},F9=function(){var a=z9();
return!!a&&3!=a.getProxyState()},t9=function(a){c8("remote",a)},r9=function(){if(!G9){var a=g.Ha("yt.mdx.remote.screenService_");
G9=a?new o9(a):null}return G9},s9=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},YYa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},ZYa=function(){return g.Ha("yt.mdx.remote.connectData_")},v9=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},z9=function(){return g.Ha("yt.mdx.remote.connection_")},E9=function(a){var b=z9();
v9(null);a||YYa("");g.Ga("yt.mdx.remote.connection_",a,void 0);q9&&(g.qc(q9,function(c){c(a)}),q9.length=0);
b&&!a?b7("yt-remote-connection-change",!1):!b&&a&&b7("yt-remote-connection-change",!0)},w9=function(){var a=g.Ny();
if(!a)return null;var b=r9();if(!b)return null;b=b.Gh();return j7(b,a)},D9=function(a,b){s9();
y9()&&y9();if(H9)B9=a;else{YYa(a.id);var c=g.Ha("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new h9(p9,a,x9(),c);a.connect(b,ZYa());a.subscribe("beforeDisconnect",function(d){b7("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){z9()&&(z9(),E9(null))});
a.subscribe("browserChannelAuthError",function(){var d=y9();d&&"shortLived"==d.idType&&(P8()?M8().handleBrowserChannelAuthError():K8("refreshLoungeToken called before API ready."))});
E9(a)}},UYa=function(){var a=w9();
a?(t9("Resume connection to: "+f7(a)),D9(a,0)):(o7(),yYa(),t9("Skipping connecting because no session screen found."))},SYa=function(){var a=x9();
if(g.Te(a)){a=m7();var b=g.Ly("yt-remote-session-name")||"",c=g.Ly("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},x9=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},I9=function(a,b,c){g.G.call(this);
var d=this;this.u=a;this.I=b;this.Vb=c;this.events=new g.HC(this);this.Z=this.events.T(this.I,"onVolumeChange",function(e){$Ya(d,e)});
this.D=!1;this.J=new g.oJ(64);this.i=new g.L(this.rO,500,this);this.B=new g.L(this.sO,1E3,this);this.S=new u7(this.xY,0,this);this.C={};this.X=new g.L(this.aP,1E3,this);this.K=new v7(this.seekTo,1E3,this);this.oa=g.Ia;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.nV);this.events.T(b,"captionschanged",this.DU);this.events.T(b,"captionssettingschanged",this.yO);this.events.T(b,"videoplayerreset",this.GA);this.events.T(b,"mdxautoplaycancel",function(){d.Vb.qK()});
a=this.Vb;a.isDisposed();a.subscribe("proxyStateChange",this.gN,this);a.subscribe("remotePlayerChange",this.Pw,this);a.subscribe("remoteQueueChange",this.GA,this);a.subscribe("previousNextChange",this.dN,this);a.subscribe("nowAutoplaying",this.XM,this);a.subscribe("autoplayDismissed",this.zM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.yO();this.GA();this.Pw()},$Ya=function(a,b){if(J9(a)){a.Vb.unsubscribe("remotePlayerChange",a.Pw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=a9(a.Vb);if(c!==d.volume||b!==d.muted)a.Vb.setVolume(c,b),a.X.start();a.Vb.subscribe("remotePlayerChange",a.Pw,a)}},aZa=function(a){a.Tb(0);
a.i.stop();a.Wb(new g.oJ(64))},K9=function(a,b){if(J9(a)&&!a.D){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.$e(c,b));a.Vb.KI(a.I.getVideoData(1).videoId,c);a.C=a9(a.Vb).trackData}},L9=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Vb.playVideo(c.videoId,b,d,e,c.playerParams,c.Za,yWa(c));a.Wb(new g.oJ(1))},bZa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{rL:1});
c&&c.length?(a.I.setOption("captions","track",b),a.D=!1):(a.I.loadModule("captions"),a.D=!0)}else a.I.setOption("captions","track",{})},J9=function(a){return a9(a.Vb).videoId===a.I.getVideoData(1).videoId},M9=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",va:"You're signed out"},{G:"div",L:"ytp-mdx-popup-description",va:"Videos that you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ja:["ytp-button","ytp-mdx-privacy-popup-cancel"],va:"Cancel"},{G:"button",Ja:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],va:"Confirm"}]}]}]});this.i=new g.UK(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},N9=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.Awa()]},{G:"div",L:"ytp-remote-display-status-text",va:"{{statustext}}"}]}]});this.api=a;this.i=new g.UK(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);cZa(this,a.Ab())},cZa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.T(b,128)?g.zH("Error on $RECEIVER_NAME",c):b.Hc()||g.T(b,4)?g.zH("Playing on $RECEIVER_NAME",c):g.zH("Connected to $RECEIVER_NAME",c);a.Qa("statustext",b);a.i.show()}else a.i.hide()},O9=function(a,b){g.AP.call(this,"Play on",0,a,b);
this.I=a;this.Lo={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},P9=function(a){g.CM.call(this,a);
this.Wk={key:h7(),name:"This computer"};this.ji=null;this.subscriptions=[];this.iG=this.Vb=null;this.Lo=[this.Wk];this.xn=this.Wk;this.Dd=new g.oJ(64);this.QL=0;this.zf=-1;this.Xw=!1;this.Vw=this.Ct=null;if(!g.rE(this.player.V())&&!g.sE(this.player.V())){a=this.player;var b=g.fM(a);b&&(b=b.Nn())&&(b=new O9(a,b),g.I(this,b));b=new N9(a);g.I(this,b);g.pM(a,b.element,4);this.Ct=new M9;g.I(this,this.Ct);g.pM(a,this.Ct.element,4);this.Xw=!!w9()}},Q9=function(a){a.Vw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Vw),a.Vw=null)},dZa=function(a,b,c){a.Dd=c;
a.player.ea("presentingplayerstatechange",new g.iH(c,b))},R9=function(a,b){if(b.key!==a.xn.key)if(b.key===a.Wk.key)C9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Xw||!a.Ct);(c?0:g.HE(a.player.V())||g.KE(a.player.V()))&&eZa(a);a.xn=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.sE(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.wM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Za,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=yWa(c))&&(a.locationInfo=c)}t9("Connecting to: "+g.Mi(b));"cast-selector-receiver"==b.key?(v9(a||null),b=a||null,P8()?M8().setLaunchParams(b):K8("setLaunchParams called before ready.")):!a&&F9()&&
s9()==b.key?b7("yt-remote-connection-change",!0):(C9(),v9(a||null),a=r9().Gh(),(b=j7(a,b.key))&&D9(b,1))}}},eZa=function(a){a.player.Ab().Hc()?a.player.pauseVideo():(a.Vw=function(b){!a.Xw&&g.kH(b,8)&&(a.player.pauseVideo(),Q9(a))},a.player.addEventListener("presentingplayerstatechange",a.Vw));
a.Ct&&a.Ct.hd();z9()||(H9=!0)},gXa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H7={"'":"\\'"},EWa={TZ:"atp",xaa:"ska",d$:"que",U7:"mus",waa:"sus",W3:"dsp",B$:"seq",x7:"mic",P2:"dpa",i_:"cds",S7:"mlm",M2:"dsdtr"};c7.prototype.equals=function(a){return a?this.id==a.id:!1};
var p7,l7="",YWa=TWa("loadCastFramework")||TWa("loadCastApplicationFramework"),$Wa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(u7,g.G);g.k=u7.prototype;g.k.YQ=function(a){this.C=arguments;this.i=!1;this.Nb?this.B=g.Sa()+this.Xf:this.Nb=g.di(this.D,this.Xf)};
g.k.stop=function(){this.Nb&&(g.C.clearTimeout(this.Nb),this.Nb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.J.apply(null,this.C)))};
g.k.ya=function(){this.stop();u7.oe.ya.call(this)};
g.k.ZQ=function(){this.Nb&&(g.C.clearTimeout(this.Nb),this.Nb=null);this.B?(this.Nb=g.di(this.D,this.B-g.Sa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.J.apply(null,this.C))};g.w(v7,g.G);g.k=v7.prototype;g.k.FI=function(a){this.B=arguments;this.Nb||this.u?this.i=!0:w7(this)};
g.k.stop=function(){this.Nb&&(g.C.clearTimeout(this.Nb),this.Nb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Nb||(this.i=!1,w7(this))};
g.k.ya=function(){g.G.prototype.ya.call(this);this.stop()};x7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
x7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var z7=new g.rf;g.w(bXa,g.ye);g.k=B7.prototype;g.k.gp=null;g.k.Nm=!1;g.k.pu=null;g.k.DH=null;g.k.Ht=null;g.k.Vt=null;g.k.fn=null;g.k.Oo=null;g.k.Cq=null;g.k.Mf=null;g.k.MB=0;g.k.Vj=null;g.k.KB=null;g.k.Wm=null;g.k.Mu=-1;g.k.eO=!0;g.k.Ap=!1;g.k.zC=0;g.k.bB=null;var eXa={},E7={};g.k=B7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.aR=function(a){a=a.target;var b=this.bB;b&&3==g.tj(a)?b.FI():this.iP(a)};
g.k.iP=function(a){try{if(a==this.Mf)a:{var b=g.tj(this.Mf),c=this.Mf.u,d=this.Mf.getStatus();if(g.Gc&&!g.zc(10)||g.ch&&!g.yc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yj(this.Mf))break a;this.Ap||4!=b||7==c||(8==c||0>=d?this.i.Jj(3):this.i.Jj(2));I7(this);var e=this.Mf.getStatus();this.Mu=e;var f=g.yj(this.Mf);if(this.Nm=200==e){4==b&&F7(this);if(this.D){for(a=!0;!this.Ap&&this.MB<f.length;){var h=fXa(this,f);if(h==E7){4==b&&(this.Wm=4,A7(15),a=!1);break}else if(h==eXa){this.Wm=4;A7(16);a=!1;
break}else J7(this,h)}4==b&&0==f.length&&(this.Wm=1,A7(17),a=!1);this.Nm=this.Nm&&a;a||(F7(this),G7(this))}else J7(this,f);this.Nm&&!this.Ap&&(4==b?this.i.qy(this):(this.Nm=!1,D7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Wm=3,A7(13)):(this.Wm=0,A7(14)),F7(this),G7(this)}}catch(l){this.Mf&&g.yj(this.Mf)}finally{}};
g.k.VW=function(a){y7((0,g.E)(this.UW,this,a),0)};
g.k.UW=function(a){this.Ap||(I7(this),J7(this,a),D7(this))};
g.k.oN=function(a){y7((0,g.E)(this.TW,this,a),0)};
g.k.TW=function(a){this.Ap||(F7(this),this.Nm=a,this.i.qy(this),this.i.Jj(4))};
g.k.cancel=function(){this.Ap=!0;F7(this)};
g.k.cX=function(){this.pu=null;var a=Date.now();0<=a-this.DH?(2!=this.Vt&&this.i.Jj(3),F7(this),this.Wm=2,A7(18),G7(this)):iXa(this,this.DH-a)};
g.k.getLastError=function(){return this.Wm};g.k=lXa.prototype;g.k.AC=null;g.k.qh=null;g.k.cB=!1;g.k.tO=null;g.k.fz=null;g.k.dF=null;g.k.BC=null;g.k.di=null;g.k.Bl=-1;g.k.Nu=null;g.k.Wu=null;g.k.connect=function(a){this.BC=a;a=L7(this.i,null,this.BC);A7(3);this.tO=Date.now();var b=this.i.S;null!=b?(this.Nu=b[0],(this.Wu=b[1])?(this.di=1,mXa(this)):(this.di=2,N7(this))):(Z6(a,"MODE","init"),this.qh=new B7(this,void 0,void 0,void 0),this.qh.gp=this.AC,C7(this.qh,a,!1,null,!0),this.di=0)};
g.k.MR=function(a){if(a)this.di=2,N7(this);else{A7(4);var b=this.i;b.nk=b.qn.Bl;U7(b,9)}a&&this.Jj(2)};
g.k.KD=function(a){return this.i.KD(a)};
g.k.abort=function(){this.qh&&(this.qh.cancel(),this.qh=null);this.Bl=-1};
g.k.vf=function(){return!1};
g.k.hN=function(a,b){this.Bl=a.Mu;if(0==this.di)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.nk=this.Bl;U7(a,2);return}this.Nu=c[0];this.Wu=c[1]}else a=this.i,a.nk=this.Bl,U7(a,2);else if(2==this.di)if(this.cB)A7(7),this.dF=Date.now();else if("11111"==b){if(A7(6),this.cB=!0,this.fz=Date.now(),a=this.fz-this.tO,!g.Gc||g.zc(10)||500>a)this.Bl=200,this.qh.cancel(),A7(12),M7(this.i,this,!0)}else A7(8),this.fz=this.dF=Date.now(),this.cB=!1};
g.k.qy=function(){this.Bl=this.qh.Mu;if(this.qh.Nm)0==this.di?this.Wu?(this.di=1,mXa(this)):(this.di=2,N7(this)):2==this.di&&((!g.Gc||g.zc(10)?!this.cB:200>this.dF-this.fz)?(A7(11),M7(this.i,this,!1)):(A7(12),M7(this.i,this,!0)));else{0==this.di?A7(9):2==this.di&&A7(10);var a=this.i;this.qh.getLastError();a.nk=this.Bl;U7(a,2)}};
g.k.zx=function(){return this.i.zx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Jj=function(a){this.i.Jj(a)};g.k=O7.prototype;g.k.lk=null;g.k.Dv=null;g.k.Wg=null;g.k.Me=null;g.k.CC=null;g.k.gz=null;g.k.EJ=null;g.k.sy=null;g.k.Cw=0;g.k.UT=0;g.k.Nf=null;g.k.Fn=null;g.k.Ll=null;g.k.Jp=null;g.k.qn=null;g.k.IB=null;g.k.Xs=-1;g.k.PL=-1;g.k.nk=-1;g.k.Cs=0;g.k.Wr=0;g.k.Bp=8;g.Ta(oXa,g.ye);g.Ta(pXa,g.ye);g.k=O7.prototype;g.k.connect=function(a,b,c,d,e){A7(0);this.CC=b;this.Dv=c||{};d&&void 0!==e&&(this.Dv.OSID=d,this.Dv.OAID=e);this.J?(y7((0,g.E)(this.aK,this,a),100),tXa(this)):this.aK(a)};
g.k.aK=function(a){this.qn=new lXa(this);this.qn.AC=this.lk;this.qn.u=this.D;this.qn.connect(a)};
g.k.vf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.mN=function(a){this.Fn=null;xXa(this,a)};
g.k.lN=function(){this.Ll=null;this.Me=new B7(this,this.B,"rpc",this.K);this.Me.gp=this.lk;this.Me.zC=0;var a=this.EJ.clone();g.Al(a,"RID","rpc");g.Al(a,"SID",this.B);g.Al(a,"CI",this.IB?"0":"1");g.Al(a,"AID",this.Xs);P7(this,a);if(!g.Gc||g.zc(10))g.Al(a,"TYPE","xmlhttp"),C7(this.Me,a,!0,this.sy,!1);else{g.Al(a,"TYPE","html");var b=this.Me,c=!!this.sy;b.Vt=3;b.fn=Y6(a.clone());hXa(b,c)}};
g.k.hN=function(a,b){if(0!=this.i&&(this.Me==a||this.Wg==a))if(this.nk=a.Mu,this.Wg==a&&3==this.i)if(7<this.Bp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Ll){if(this.Me)if(this.Me.Ht+3E3<this.Wg.Ht)R7(this),this.Me.cancel(),this.Me=null;else break a;T7(this);A7(19)}}else this.PL=a[1],0<this.PL-this.Xs&&37500>a[2]&&this.IB&&0==this.Wr&&!this.Jp&&(this.Jp=y7((0,g.E)(this.AU,this),6E3));else U7(this,11)}else null!=b&&U7(this,11);else if(this.Me==
a&&R7(this),!g.fb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Xs=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.sy=c[2],c=c[3],null!=c?this.Bp=c:this.Bp=6,this.i=3,this.Nf&&this.Nf.WJ(),this.EJ=L7(this,this.zx()?this.sy:null,this.CC),yXa(this)):"stop"==c[0]&&U7(this,7):3==this.i&&("stop"==c[0]?U7(this,7):"noop"!=c[0]&&this.Nf&&this.Nf.VJ(c),this.Wr=0)};
g.k.AU=function(){null!=this.Jp&&(this.Jp=null,this.Me.cancel(),this.Me=null,T7(this),A7(20))};
g.k.qy=function(a){if(this.Me==a){R7(this);this.Me=null;var b=2}else if(this.Wg==a)this.Wg=null,b=1;else return;this.nk=a.Mu;if(0!=this.i)if(a.Nm)if(1==b){b=Date.now()-a.Ht;var c=z7;c.dispatchEvent(new oXa(c,a.Cq?a.Cq.length:0,b,this.Cs));Q7(this);this.C.length=0}else yXa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.nk)){if(d=1==b)this.Wg||this.Fn||1==this.i||2<=this.Cs?d=!1:(this.Fn=y7((0,g.E)(this.mN,this,a),zXa(this,this.Cs)),this.Cs++,d=!0);d=!(d||2==b&&T7(this))}if(d)switch(c){case 1:U7(this,
5);break;case 4:U7(this,10);break;case 3:U7(this,6);break;case 7:U7(this,12);break;default:U7(this,2)}}};
g.k.lS=function(a){if(!g.Zb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.fY=function(a){a?A7(2):(A7(1),AXa(this,8))};
g.k.KD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.nj;a.S=!1;return a};
g.k.isActive=function(){return!!this.Nf&&this.Nf.isActive(this)};
g.k.Jj=function(a){var b=z7;b.dispatchEvent(new pXa(b,a))};
g.k.zx=function(){return!(!g.Gc||g.zc(10))};
g.k=BXa.prototype;g.k.WJ=function(){};
g.k.VJ=function(){};
g.k.UJ=function(){};
g.k.wD=function(){};
g.k.HK=function(){return{}};
g.k.isActive=function(){return!0};g.k=CXa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.Zb(this.i,a)||g.Zb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.tQa)(b,a);0<=c?(g.bc(b,c),b=!0):b=!1;return b||g.cc(this.u,a)};
g.k.Bi=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(V7,g.G);g.k=V7.prototype;g.k.MW=function(){this.Xf=Math.min(3E5,2*this.Xf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Xf+15E3*Math.random();g.Wr(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Xf=5E3};g.Ta(W7,BXa);g.k=W7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.fg=function(a){return this.B.fg(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.Z||(this.Z=!0,g.ve(this.B),FXa(this),g.ve(this.u),this.u=null,this.oa=function(){return""})};
g.k.isDisposed=function(){return this.Z};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.xa+"/test";b=this.xa+"/bind";var d=new O7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Nf=null);d.Nf=this;this.i=d;X7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.lk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.lk=f}e?(3!=e.getState()&&0==vXa(e)||e.getState(),this.i.connect(a,b,this.J,e.B,e.Xs)):c?this.i.connect(a,
b,this.J,c.sessionId,c.arrayId):this.i.connect(a,b,this.J)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.$e(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):Y7(this)&&(X7(this),uXa(this.i,a))};
g.k.WJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)uXa(this.i,a[b])}this.ea("handlerOpened")};
g.k.UJ=function(a){var b=2==a&&401==this.i.nk;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.wD=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.HK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.$e(a,this.D);return a};
g.k.VJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),sXa(this.i)):this.ea("handlerMessage",new DXa(a[0],a[1]))};
g.k.nB=function(a){(this.J.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.lk||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.lk=b}};
g.k.HX=function(){this.u.isActive();0==vXa(this.i)&&this.connect(this.D,this.C)};Z7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z7.prototype.D=function(a){a(Error("request timed out"))};var MXa=Date.now(),b8=null,e8=Array(50),d8=-1,f8=!1;g.Ta(g8,g.Xx);g8.prototype.Gh=function(){return this.screens};
g8.prototype.contains=function(a){return!!i7(this.screens,a)};
g8.prototype.get=function(a){return a?j7(this.screens,a):null};
g8.prototype.info=function(a){c8(this.J,a)};g.w(h8,g.Xx);g.k=h8.prototype;g.k.start=function(){!this.i&&isNaN(this.Nb)&&this.yN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Nb)||(g.ju(this.Nb),this.Nb=NaN)};
g.k.ya=function(){this.stop();g.Xx.prototype.ya.call(this)};
g.k.yN=function(){this.Nb=NaN;this.i=g.nu($7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.E)(this.cR,this),onError:(0,g.E)(this.bR,this),onTimeout:(0,g.E)(this.dR,this)})};
g.k.cR=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.J;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new d7(a),b)};
g.k.bR=function(a){this.i=null;a.status&&404==a.status?this.u>=fZa.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=fZa[this.u],this.Nb=g.hu((0,g.E)(this.yN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.dR=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var fZa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(j8,g8);g.k=j8.prototype;g.k.start=function(){i8(this)&&this.ea("screenChange");!g.Ly("yt-remote-lounge-token-expiration")&&QXa(this);g.ju(this.i);this.i=g.hu((0,g.E)(this.start,this),1E4)};
g.k.add=function(a,b){i8(this);NXa(this,a);k8(this,!1);this.ea("screenChange");b(a);a.token||QXa(this)};
g.k.remove=function(a,b){var c=i8(this);PXa(this,a)&&(k8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.GB=function(a,b,c,d){var e=i8(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.ya=function(){g.ju(this.i);j8.oe.ya.call(this)};
g.k.MS=function(a){i8(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k8(this,!b);b&&c8(this.J,"Missed "+b+" lounge tokens.")};
g.k.LS=function(a){c8(this.J,"Requesting lounge tokens failed: "+a)};g.w(m8,g.Xx);g.k=m8.prototype;g.k.start=function(){var a=parseInt(g.Ly("yt-remote-fast-check-period")||"0",10);(this.C=g.Sa()-144E5<a?0:a)?p8(this):(this.C=g.Sa()+3E5,g.Ky("yt-remote-fast-check-period",this.C),this.uG())};
g.k.isEmpty=function(){return g.Te(this.i)};
g.k.update=function(){l8("Updating availability on schedule.");var a=this.J(),b=g.He(this.i,function(c,d){return c&&!!j7(a,d)},this);
o8(this,b)};
g.k.ya=function(){g.ju(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.Xx.prototype.ya.call(this)};
g.k.uG=function(){g.ju(this.B);this.B=NaN;this.u&&this.u.abort();var a=SXa(this);if($6(a)){var b=$7(this.D,"/pairing/get_screen_availability");this.u=a8(this.D,b,{lounge_token:g.Oe(a).join(",")},(0,g.E)(this.qW,this,a),(0,g.E)(this.pW,this))}else o8(this,{}),p8(this)};
g.k.qW=function(a,b){this.u=null;var c=g.Oe(SXa(this));if(g.oc(c,g.Oe(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;o8(this,c);p8(this)}else this.pe("Changing Screen set during request."),this.uG()};
g.k.pW=function(a){this.pe("Screen availability failed: "+a);this.u=null;p8(this)};
g.k.pe=function(a){c8("OnlineScreenService",a)};g.Ta(q8,g8);g.k=q8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.GB=function(a,b,c,d){this.u.contains(a)?this.u.GB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c8(this.J,a),d(Error(a)))};
g.k.Gh=function(a){return a?this.screens:g.ec(this.screens,g.iq(this.B,function(b){return!this.contains(b)},this))};
g.k.GI=function(){return g.iq(this.Gh(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.HI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new h8(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.ve(l);e(r8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.ve(l);f(m)});
l.start();return(0,g.E)(l.stop,l)};
g.k.eR=function(a,b,c,d){g.nu($7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.E)(function(e,f){e=new d7(f.screen||{});if(!e.name||WXa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);WXa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(r8(this,e))},this),
onError:(0,g.E)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.E)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ya=function(){g.ve(this.u);g.ve(this.i);q8.oe.ya.call(this)};
g.k.WS=function(){YXa(this);this.ea("screenChange");this.i.update()};
q8.prototype.dispose=q8.prototype.dispose;g.Ta(t8,g.Xx);g.k=t8.prototype;g.k.getScreen=function(){return this.C};
g.k.Ag=function(a){this.isDisposed()||(a&&(v8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){c8(this.Ba,a)};
g.k.II=function(){return null};
g.k.JG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.E)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.E)(function(){v8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ya=function(){this.JG("");t8.oe.ya.call(this)};g.w(w8,t8);g.k=w8.prototype;g.k.IG=function(a){if(this.u){if(this.u==a)return;v8(this,"Overriding cast session with new session object");gYa(this);this.xa=!1;this.X="unknown";this.u.removeUpdateListener(this.oa);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.oa);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);cYa(this,"getMdxSessionStatus")};
g.k.Ys=function(a){this.info("launchWithParams no-op for Cast: "+g.Mi(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.E)(function(){this.Ag()},this),(0,g.E)(function(){this.Ag(Error("Failed to stop receiver app."))},this)):this.Ag(Error("Stopping cast device without session."))};
g.k.JG=function(){};
g.k.ya=function(){this.info("disposeInternal");gYa(this);this.u&&(this.u.removeUpdateListener(this.oa),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;t8.prototype.ya.call(this)};
g.k.gX=function(a,b){if(!this.isDisposed())if(b)if(b=a7(b),g.Na(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Mi(b)),a){case "mdxSessionStatus":aYa(this,b);break;case "loungeToken":dYa(this,b);break;default:v8(this,"Unknown youtube message: "+a)}else v8(this,"Unable to parse message.");else v8(this,"No data in message.")};
g.k.UK=function(a,b,c,d){g.ju(this.S);this.S=0;VXa(this.B,this.i.label,a,this.i.friendlyName,(0,g.E)(function(e){e?b(e):0<=d?(v8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.hu((0,g.E)(this.UK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.II=function(){return this.u};
g.k.fR=function(a){this.isDisposed()||a||(v8(this,"Cast session died."),this.Ag())};g.w(z8,t8);g.k=z8.prototype;g.k.IG=function(a){this.u=a;this.u.addUpdateListener(this.Ia)};
g.k.Ys=function(a){this.Ka=a;this.Z()};
g.k.stop=function(){nYa(this);this.u?this.u.stop((0,g.E)(this.Ag,this,null),(0,g.E)(this.Ag,this,"Failed to stop DIAL device.")):this.Ag()};
g.k.ya=function(){nYa(this);this.u&&this.u.removeUpdateListener(this.Ia);this.u=null;t8.prototype.ya.call(this)};
g.k.gR=function(a){this.isDisposed()||a||(v8(this,"DIAL session died."),this.D(),this.D=g.Ia,this.Ag())};g.w(D8,t8);D8.prototype.stop=function(){this.Ag()};
D8.prototype.IG=function(){};
D8.prototype.Ys=function(){g.ju(this.u);this.u=NaN;var a=j7(this.B.Gh(),this.i.label);a?u8(this,a):this.Ag(Error("No such screen"))};
D8.prototype.ya=function(){g.ju(this.u);this.u=NaN;t8.prototype.ya.call(this)};g.w(E8,g.Xx);g.k=E8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.J?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.E)(this.bW,this);c=new chrome.cast.ApiConfig(c,(0,g.E)(this.iN,this),e,d,a);c.customDialLaunchCallback=(0,g.E)(this.VU,this);
chrome.cast.initialize(c,(0,g.E)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),JXa(),this.u.subscribe("onlineScreenChange",(0,g.E)(this.JI,this)),this.B=qYa(this),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(f){this.pe("Failed to set initial custom receivers: "+g.Mi(f))},this)),this.ea("yt-remote-cast2-availability-change",G8(this)),b(!0))},this),(0,g.E)(function(f){this.pe("Failed to initialize API: "+g.Mi(f));
b(!1)},this))};
g.k.LX=function(a,b){F8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)F8("Unsetting old screen status: "+this.i.i.friendlyName),H8(this,null)}if(a&&b){if(!this.i){c=j7(this.u.Gh(),a);if(!c){F8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){F8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=oYa(this,c);a||(F8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(d){this.pe("Failed to set initial custom receivers: "+g.Mi(d))},this)));
F8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);H8(this,new D8(this.u,a),!0)}this.i.JG(b)}else F8("setConnectedScreenStatus: no screen.")};
g.k.MX=function(a){this.isDisposed()?this.pe("Setting connection data on disposed cast v2"):this.i?this.i.Ys(a):this.pe("Setting connection data without a session")};
g.k.iR=function(){this.isDisposed()?this.pe("Stopping session on disposed cast v2"):this.i?(this.i.stop(),H8(this,null)):F8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.E)(this.iN,this),(0,g.E)(this.tW,this))};
g.k.ya=function(){this.u.unsubscribe("onlineScreenChange",(0,g.E)(this.JI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=GXa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.cc(b||[],a);g.ve(this.i);g.Xx.prototype.ya.call(this)};
g.k.pe=function(a){c8("Controller",a)};
g.k.kN=function(a,b){this.i==a&&(b||H8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.YV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)F8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{F8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H8(this,
new D8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H8(this,new z8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:H8(this,new w8(this.u,a,this.config_));break;default:this.pe("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.pe("Stopping receiver w/o session: "+a.friendlyName)}else this.pe("onReceiverAction_ called without receiver.")};
g.k.VU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pe("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.pe("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return F8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pe('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H8(this,new z8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,A8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=kYa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.St(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=lYa(b,c)):a=lYa(b,c)):a=C8(b);return a};
g.k.iN=function(a){var b=this;if(!this.isDisposed()&&!this.J){F8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)F8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),H8(this,new w8(this.u,c,this.config_),!0);else{this.pe("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=j7(this.u.Gh(),
d.label);e&&e7(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(F8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.ve(this.i),this.i=new w8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.E)(this.kN,this,this.i)),this.i.subscribe("sessionFailed",function(){return pYa(b,b.i)}),this.i.Ys(null));
this.i.IG(a)}}};
g.k.hR=function(){return this.i?this.i.II():null};
g.k.tW=function(a){this.isDisposed()||(this.pe("Failed to estabilish a session: "+g.Mi(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.bW=function(a){F8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=G8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;G8(this)!=b&&this.ea("yt-remote-cast2-availability-change",G8(this))}};
g.k.JI=function(){this.isDisposed()||(this.B=qYa(this),F8("Updating custom receivers: "+g.Mi(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ia,(0,g.E)(function(){this.pe("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",G8(this)))};
E8.prototype.setLaunchParams=E8.prototype.MX;E8.prototype.setConnectedScreenStatus=E8.prototype.LX;E8.prototype.stopSession=E8.prototype.iR;E8.prototype.getCastSession=E8.prototype.hR;E8.prototype.requestSession=E8.prototype.requestSession;E8.prototype.init=E8.prototype.init;E8.prototype.dispose=E8.prototype.dispose;var N8=[];g.k=S8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Pk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Hc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Rj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+U8(this):this.D};
g.k.clone=function(){return new S8(Y8(this))};g.w($8,g.Xx);g.k=$8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){b9(this)?(this.i?this.i.play(null,g.Ia,g9(this,"play")):f9(this,"play"),e9(this,1,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.play)};
g.k.pause=function(){b9(this)?(this.i?this.i.pause(null,g.Ia,g9(this,"pause")):f9(this,"pause"),e9(this,2,W8(a9(this))),this.ea("remotePlayerChange")):c9(this,this.pause)};
g.k.seekTo=function(a){if(b9(this)){if(this.i){var b=a9(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Hc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,g9(this,"seekTo",{newTime:a}))}else f9(this,"seekTo",{newTime:a});e9(this,3,a);this.ea("remotePlayerChange")}else c9(this,g.Ra(this.seekTo,a))};
g.k.stop=function(){if(b9(this)){this.i?this.i.stop(null,g.Ia,g9(this,"stopVideo")):f9(this,"stopVideo");var a=a9(this);a.index=-1;a.videoId="";T8(a);d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.stop)};
g.k.setVolume=function(a,b){if(b9(this)){var c=a9(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.E)(function(){c8("CP","set receiver volume: "+d)},this),(0,g.E)(function(){this.pe("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.E)(function(){c8("CP","set receiver muted: "+b)},this),(0,g.E)(function(){this.pe("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f9(this,"setVolume",e)}c.muted=b;c.volume=a;d9(this,c)}else c9(this,g.Ra(this.setVolume,a,b))};
g.k.KI=function(a,b){if(b9(this)){var c=a9(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Mi(b.style),g.$e(a,c.trackData));f9(this,"setSubtitlesTrack",a);d9(this,c)}else c9(this,g.Ra(this.KI,a,b))};
g.k.setAudioTrack=function(a,b){b9(this)?(b=b.getLanguageInfo().getId(),f9(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=a9(this),a.audioTrackId=b,d9(this,a)):c9(this,g.Ra(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=a9(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);X8(l,a,c||0);void 0!==b&&(V8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.Mi(h));f9(this,"setPlaylist",m);d||d9(this,l)};
g.k.UA=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"previous")}else c9(this,g.Ra(this.UA,a,b))};
g.k.nextVideo=function(a,b){if(b9(this)){if(a&&b){var c=a9(this);X8(c,a,b);d9(this,c)}f9(this,"next")}else c9(this,g.Ra(this.nextVideo,a,b))};
g.k.Zr=function(){if(b9(this)){f9(this,"clearPlaylist");var a=a9(this);a.reset();d9(this,a);this.ea("remotePlayerChange")}else c9(this,this.Zr)};
g.k.qK=function(){b9(this)?f9(this,"dismissAutoplay"):c9(this,this.qK)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.Xx.prototype.dispose.call(this)};
g.k.ya=function(){CYa(this);this.C=null;this.D.clear();Z8(this,null);g.Xx.prototype.ya.call(this)};
g.k.KG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.WV=function(a,b){this.ea(a,b)};
g.k.GU=function(a){if(!a)this.Lw(null),Z8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=a9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c8("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d9(this,b)}};
g.k.Lw=function(a){c8("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),DYa(this),this.ea("remotePlayerChange")};
g.k.FU=function(a){a?(DYa(this),this.ea("remotePlayerChange")):this.Lw(null)};
g.k.fH=function(){f9(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.NU=function(){var a=zYa();a&&Z8(this,a)};
g.k.pe=function(a){c8("CP",a)};g.w(h9,g.Xx);g.k=h9.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.wc.listId=c);this.wc.videoId=d;this.wc.index=l||0;this.wc.state=3;V8(this.wc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";i9("Connecting with "+c+" and params: "+g.Mi(m));this.i.connect({method:c,params:g.Mi(m)},a,MWa())}else i9("Connecting without params"),this.i.connect({},a,MWa());GYa(this)};
g.k.nB=function(a){this.i.nB(a)};
g.k.dispose=function(){this.isDisposed()||(g.Ga("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),j9(this,3));g.Xx.prototype.dispose.call(this)};
g.k.ya=function(){k9(this);m9(this);l9(this);g.ju(this.K);this.K=NaN;g.ju(this.S);this.S=NaN;this.B=null;g.iv(this.X);this.X.length=0;this.i.dispose();g.Xx.prototype.ya.call(this);this.C=this.J=this.u=this.wc=this.i=null};
g.k.HS=function(){this.ys(2)};
g.k.KU=function(){i9("Channel opened");this.xa&&(this.xa=!1,l9(this),this.oa=g.hu((0,g.E)(function(){i9("Timing out waiting for a screen.");this.ys(1)},this),15E3));
QWa(EXa(this.i),this.Ka)};
g.k.HU=function(){i9("Channel closed");isNaN(this.D)?o7(!0):o7();this.dispose()};
g.k.IU=function(a,b){o7();isNaN(this.Sv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),i9("Channel error: "+a+" without reconnection"),this.dispose()):(this.xa=!0,i9("Channel error: "+a+" with reconnection in "+this.Sv()+" ms"),j9(this,2))};
g.k.zL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.q(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.JU=function(a){a.params?i9("Received: action="+a.action+", params="+g.Mi(a.params)):i9("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=a7(a.params.devices);this.u=g.Vn(a,function(c){return new c7(c)});
a=!!g.Ub(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
JYa(this,a);a=this.zL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.dc(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
JYa(this,!1);break;case "remoteConnected":var b=new c7(a7(a.params.device));g.Ub(this.u,function(c){return c.equals(b)})||zWa(this.u,b);
break;case "remoteDisconnected":b=new c7(a7(a.params.device));g.dc(this.u,function(c){return c.equals(b)});
break;case "gracefulDisconnect":break;case "playlistModified":LYa(this,a,"QUEUE_MODIFIED");break;case "nowPlaying":NYa(this,a);break;case "onStateChange":MYa(this,a);break;case "onAdStateChange":OYa(this,a);break;case "onVolumeChanged":PYa(this,a);break;case "onSubtitlesTrackChanged":KYa(this,a);break;case "nowAutoplaying":QYa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.J=a.params.videoId||null;this.ea("autoplayUpNext",this.J);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":RYa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:i9("Unrecognized action: "+a.action)}};
g.k.BX=function(){if(this.B){var a=this.B;this.B=null;this.wc.videoId!=a&&n9(this,"getNowPlaying")}};
g.k.DS=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Sv())?Y7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.ys=function(a){i9("Disconnecting with "+a);g.Ga("yt.mdx.remote.remoteClient_",null,void 0);k9(this);this.ea("beforeDisconnect",a);1==a&&o7();FXa(this.i,a);this.dispose()};
g.k.BS=function(){var a=this.wc;this.B&&(a=this.wc.clone(),X8(a,this.B,a.index));return Y8(a)};
g.k.OX=function(a){var b=new S8(a);b.videoId&&b.videoId!=this.wc.videoId&&(this.B=b.videoId,g.ju(this.K),this.K=g.hu((0,g.E)(this.BX,this),5E3));var c=[];this.wc.listId==b.listId&&this.wc.videoId==b.videoId&&this.wc.index==b.index||c.push("remoteQueueChange");this.wc.playerState==b.playerState&&this.wc.volume==b.volume&&this.wc.muted==b.muted&&W8(this.wc)==W8(b)&&g.Mi(this.wc.trackData)==g.Mi(b.trackData)||c.push("remotePlayerChange");this.wc.reset(a);g.qc(c,function(d){this.ea(d)},this)};
g.k.TK=function(){var a=this.i.J.id,b=g.Ub(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Sv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.yS=function(){return this.C||"UNSUPPORTED"};
g.k.zS=function(){return this.J||""};
g.k.jR=function(){if(!isNaN(this.Sv())){var a=this.i.u;g.Xr(a.i);a.start()}};
g.k.KX=function(a,b){n9(this,a,b);IYa(this)};
g.k.LI=function(){var a=g.Eu("SID","")||"",b=g.Eu("SAPISID","")||"",c=g.Eu("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.Cc(g.cb(a),2);b=g.Cc(g.cb(b),2);c=g.Cc(g.cb(c),2);return g.Cc(g.cb(a+","+b+","+c),2)};
h9.prototype.subscribe=h9.prototype.subscribe;h9.prototype.unsubscribeByKey=h9.prototype.fg;h9.prototype.getProxyState=h9.prototype.DS;h9.prototype.disconnect=h9.prototype.ys;h9.prototype.getPlayerContextData=h9.prototype.BS;h9.prototype.setPlayerContextData=h9.prototype.OX;h9.prototype.getOtherConnectedRemoteId=h9.prototype.TK;h9.prototype.getReconnectTimeout=h9.prototype.Sv;h9.prototype.getAutoplayMode=h9.prototype.yS;h9.prototype.getAutoplayVideoId=h9.prototype.zS;h9.prototype.reconnect=h9.prototype.jR;
h9.prototype.sendMessage=h9.prototype.KX;h9.prototype.getXsrfToken=h9.prototype.LI;h9.prototype.isCapabilitySupportedOnConnectedDevices=h9.prototype.zL;g.w(o9,g8);g.k=o9.prototype;g.k.Gh=function(a){return this.Ue.$_gs(a)};
g.k.contains=function(a){return!!this.Ue.$_c(a)};
g.k.get=function(a){return this.Ue.$_g(a)};
g.k.start=function(){this.Ue.$_st()};
g.k.add=function(a,b,c){this.Ue.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ue.$_r(a,b,c)};
g.k.GB=function(a,b,c,d){this.Ue.$_un(a,b,c,d)};
g.k.ya=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ue.$_ubk(this.i[a]);this.i.length=0;this.Ue=null;g8.prototype.ya.call(this)};
g.k.DP=function(){this.ea("screenChange")};
g.k.CV=function(){this.ea("onlineScreenChange")};
q8.prototype.$_st=q8.prototype.start;q8.prototype.$_gspc=q8.prototype.eR;q8.prototype.$_gsppc=q8.prototype.HI;q8.prototype.$_c=q8.prototype.contains;q8.prototype.$_g=q8.prototype.get;q8.prototype.$_a=q8.prototype.add;q8.prototype.$_un=q8.prototype.GB;q8.prototype.$_r=q8.prototype.remove;q8.prototype.$_gs=q8.prototype.Gh;q8.prototype.$_gos=q8.prototype.GI;q8.prototype.$_s=q8.prototype.subscribe;q8.prototype.$_ubk=q8.prototype.fg;var B9=null,H9=!1,p9=null,q9=null,G9=null,u9=[];g.w(I9,g.G);g.k=I9.prototype;g.k.ya=function(){g.G.prototype.ya.call(this);this.i.stop();this.B.stop();this.S.stop();this.oa();var a=this.Vb;a.unsubscribe("proxyStateChange",this.gN,this);a.unsubscribe("remotePlayerChange",this.Pw,this);a.unsubscribe("remoteQueueChange",this.GA,this);a.unsubscribe("previousNextChange",this.dN,this);a.unsubscribe("nowAutoplaying",this.XM,this);a.unsubscribe("autoplayDismissed",this.zM,this);this.Vb=this.u=null};
g.k.Bj=function(a){var b=g.Aa.apply(1,arguments);if(2!=this.Vb.B)if(J9(this)){var c=a;if(!a9(this.Vb).isAdPlaying()||"control_seek"!==c)switch(c){case "control_toggle_play_pause":a9(this.Vb).Hc()?this.Vb.pause():this.Vb.play();break;case "control_play":this.Vb.play();break;case "control_pause":this.Vb.pause();break;case "control_seek":this.K.FI(b[0],b[1]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b=
this.I.getCurrentTime();L9(this,0===b?void 0:b);break;case "control_seek":L9(this,b[0]);break;case "control_subtitles_set_track":K9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}};
g.k.DU=function(a){this.S.YQ(a)};
g.k.xY=function(a){this.Bj("control_subtitles_set_track",g.Te(a)?null:a)};
g.k.yO=function(){var a=this.I.getOption("captions","track");g.Te(a)||K9(this,a)};
g.k.Tb=function(a){this.u.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.nV=function(){g.Te(this.C)||bZa(this,this.C);this.D=!1};
g.k.gN=function(a,b){this.B.stop();2===b&&this.sO()};
g.k.Pw=function(){if(J9(this)){this.i.stop();var a=a9(this.Vb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.zf=1;break;case 1082:case 1083:this.u.zf=0;break;default:this.u.zf=-1}switch(a.playerState){case 1081:case 1:this.Wb(new g.oJ(8));this.rO();break;case 1085:case 3:this.Wb(new g.oJ(9));break;case 1083:case 0:this.Wb(new g.oJ(2));this.K.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Wb(new g.oJ(4));break;case 2:this.Wb(new g.oJ(4));this.Tb(W8(a));
break;case -1:this.Wb(new g.oJ(64));break;case -1E3:this.Wb(new g.oJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a9(this.Vb).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,bZa(this,a));a=a9(this.Vb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.X.isActive()||this.aP()}else aZa(this)};
g.k.dN=function(){this.I.ea("mdxpreviousnextchange")};
g.k.GA=function(){J9(this)||aZa(this)};
g.k.XM=function(a){isNaN(a)||this.I.ea("mdxnowautoplaying",a)};
g.k.zM=function(){this.I.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J9(this)&&this.Vb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a9(this.Vb).playerState?L9(this,a):b&&this.Vb.seekTo(a)};
g.k.aP=function(){var a=this;if(J9(this)){var b=a9(this.Vb);this.events.xc(this.Z);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.Z=this.events.T(this.I,"onVolumeChange",function(c){$Ya(a,c)})}};
g.k.rO=function(){this.i.stop();if(!this.Vb.isDisposed()){var a=a9(this.Vb);a.Hc()&&this.Wb(new g.oJ(8));this.Tb(W8(a));this.i.start()}};
g.k.sO=function(){this.B.stop();this.i.stop();var a=this.Vb.C.getReconnectTimeout();2==this.Vb.B&&!isNaN(a)&&this.B.start()};
g.k.Wb=function(a){this.B.stop();var b=this.J;if(!g.tJ(b,a)){var c=g.T(a,2);c!==g.T(this.J,2)&&this.I.Nt(c);this.J=a;dZa(this.u,b,a)}};g.w(M9,g.V);M9.prototype.hd=function(){this.i.show()};
M9.prototype.Db=function(){this.i.hide()};
M9.prototype.u=function(){b7("mdx-privacy-popup-cancel");this.Db()};
M9.prototype.B=function(){b7("mdx-privacy-popup-confirm");this.Db()};g.w(N9,g.V);N9.prototype.onStateChange=function(a){cZa(this,a.state)};g.w(O9,g.AP);O9.prototype.D=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Lo=g.rc(a,this.i,this),g.BP(this,g.Vn(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.ai(a),this.enable(!0)):this.enable(!1)};
O9.prototype.i=function(a){return a.key};
O9.prototype.sj=function(a){return"cast-selector-receiver"===a?"Cast...":this.Lo[a].name};
O9.prototype.Ef=function(a){g.AP.prototype.Ef.call(this,a);this.I.setOption("remote","currentReceiver",this.Lo[a]);this.vb.Db()};g.w(P9,g.CM);g.k=P9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.pE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};VYa(b,a);this.subscriptions.push(g.Ev("yt-remote-before-disconnect",this.CU,this));this.subscriptions.push(g.Ev("yt-remote-connection-change",this.cW,this));this.subscriptions.push(g.Ev("yt-remote-receiver-availability-change",this.fN,
this));this.subscriptions.push(g.Ev("yt-remote-auto-connect",this.aW,this));this.subscriptions.push(g.Ev("yt-remote-receiver-resumed",this.ZV,this));this.subscriptions.push(g.Ev("mdx-privacy-popup-confirm",this.qX,this));this.subscriptions.push(g.Ev("mdx-privacy-popup-cancel",this.pX,this));this.fN()};
g.k.load=function(){this.player.cancelPlayback();g.CM.prototype.load.call(this);this.ji=new I9(this,this.player,this.Vb);var a=(a=ZYa())?a.currentTime:0;var b=F9()?new $8(z9(),void 0):null;0==a&&b&&(a=W8(a9(b)));0!==a&&this.Tb(a);dZa(this,this.Dd,this.Dd);this.player.il(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.xn=this.Wk;(0,g.we)(this.ji,this.Vb);this.Vb=this.ji=null;g.CM.prototype.unload.call(this);this.player.il(5);Q9(this)};
g.k.ya=function(){g.Fv(this.subscriptions);g.CM.prototype.ya.call(this)};
g.k.Xk=function(a){var b=g.Aa.apply(1,arguments);this.loaded&&this.ji.Bj.apply(this.ji,[a].concat(g.u(b)))};
g.k.getAdState=function(){return this.zf};
g.k.Pk=function(){return this.Vb?a9(this.Vb).Pk:!1};
g.k.hasNext=function(){return this.Vb?a9(this.Vb).hasNext:!1};
g.k.Tb=function(a,b){this.QL=a||0;this.player.ea("progresssync",a,b);this.player.Pa("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.QL};
g.k.getProgressState=function(){var a=a9(this.Vb),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.wf():!a.isAdPlaying()&&this.player.wf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+U8(a):a.B,isAtLiveHead:1>=(a.u?a.i+U8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+U8(a):a.i,seekableStart:0<
a.C?a.C+U8(a):a.C}};
g.k.nextVideo=function(){this.Vb&&this.Vb.nextVideo()};
g.k.UA=function(){this.Vb&&this.Vb.UA()};
g.k.CU=function(a){1===a&&(this.iG=this.Vb?a9(this.Vb):null)};
g.k.cW=function(){var a=F9()?new $8(z9(),void 0):null;if(a){var b=this.xn;this.loaded&&this.unload();this.Vb=a;this.iG=null;b.key!==this.Wk.key&&(this.xn=b,this.load())}else(0,g.ve)(this.Vb),this.Vb=null,this.loaded&&(this.unload(),(a=this.iG)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.fN=function(){var a=[this.Wk],b=a.concat,c=WYa();O8()&&g.Ly("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Lo=b.call(a,c);a=A9()||this.Wk;R9(this,a);this.player.Pa("onMdxReceiversChange")};
g.k.aW=function(){var a=A9();R9(this,a)};
g.k.ZV=function(){this.xn=A9()};
g.k.qX=function(){this.Xw=!0;Q9(this);H9=!1;B9&&D9(B9,1);B9=null};
g.k.pX=function(){this.Xw=!1;Q9(this);R9(this,this.Wk);this.xn=this.Wk;H9=!1;B9=null;this.player.playVideo()};
g.k.nf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Lo;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q8():R9(this,b)),this.loaded?this.xn:this.Wk;case "quickCast":return 2===this.Lo.length&&"cast-selector-receiver"===this.Lo[1].key?(b&&Q8(),!0):!1}};
g.k.fH=function(){this.Vb.fH()};
g.k.Wi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.BM("remote",P9);})(_yt_player);
